### ISSUE TITLE
اسکرول نشدن تنظیمات 

### ISSUE THREAD

**Issue by ialireza** [bepass-org/oblivion#10]
![Screenshot_20240211-182116](https://github.com/bepass-org/oblivion/assets/26402782/90095ddb-ba4b-4142-b528-4e2238e3638b)

اسکرول صفحه در اندروید ۷ کار نمیکند

**Comment by vaccine919** [comment]
https://github.com/bepass-org/oblivion/pull/15

**Comment by Ali242475** [comment]
![Uploading 387623529_1133906904660961_6614580429168916401_n.jpg…]()
