### ISSUE TITLE
I fuond somthing similar

### ISSUE THREAD

**Issue by amirgh9367** [bepass-org/oblivion#102]
salam mn dashtam to github micharkhidam ke be in barkhordam https://github.com/ViRb3/wgcf y chiziye mels app shoma vali cross platforme testsh kardam roye windows vali kar nakard mikhastam bedon chetore ke y sourcan vali on kar mikone in na ?

**Comment by femdiya** [comment]
> salam mn dashtam to github micharkhidam ke be in barkhordam https://github.com/ViRb3/wgcf y chiziye mels app shoma vali cross platforme testsh kardam roye windows vali kar nakard mikhastam bedon chetore ke y sourcan vali on kar mikone in na ?

این یه زمانی کار میکرد، پروتکولش وایرگارده. میزدم Allow untunnled traffic کار میکرد، فکر نکنم هنوز عمل کنه.

**Comment by amijafi** [comment]
vijegi khase oblivion ine ke noise ezafe mikone be handshake wireguard ( inja wirgaurd cloudflare ya hamoon warp ) ta filtering ro gool bezane va rad beshe va handshake anjam beshe , uni ke shome eshare mikoni ye impelement az warp va wireguard standard hast
