### ISSUE TITLE
[Question] How to use the "Connect via LAN" feature?

### ISSUE THREAD

**Issue by inattentive-nerd** [bepass-org/oblivion#103]
Sorry if this is unrelated but, I can't get that feature to work for me.

**Comment by femdiya** [comment]
Which part of feature doesn't work for you?

**Comment by JJHACKER** [comment]
I have same question , how to use Connect via LAN" feature ?
Can i connect from pc in lan to mobile ?

**Comment by inattentive-nerd** [comment]
> Which part of feature doesn't work for you?

It just doesn't work. I turn on my hotspot, then I turn on the feature and then I connect the VPN, but other machines on my network are still behind the Islamic republic's firewall.
Maybe I am just dumb and I am using it wrong; if this is the case please teach me. Sorry.

**Comment by JJHACKER** [comment]
> > Which part of feature doesn't work for you?
> 
> It just doesn't work. I turn on my hotspot, then I turn on the feature and then I connect the VPN, but other machines on my network are still behind the Islamic republic's firewall. Maybe I am just dumb and I am using it wrong; if this is the case please teach me. Sorry.

Use socks droid
https://apkcombo.com/socksdroid/net.typeblog.socks/
other user must install this then , ip = your mobile ip in lan / port = 8086

**Comment by inattentive-nerd** [comment]
> > > Which part of feature doesn't work for you?
> > 
> > 
> > It just doesn't work. I turn on my hotspot, then I turn on the feature and then I connect the VPN, but other machines on my network are still behind the Islamic republic's firewall. Maybe I am just dumb and I am using it wrong; if this is the case please teach me. Sorry.
> 
> Use socks droid https://apkcombo.com/socksdroid/net.typeblog.socks/ other user must install this then , ip = your mobile ip in lan / port = 8086

It is possible to do it without that app too. Thanks now I understand how to use it.
