### ISSUE TITLE
قابلیت اضافه کردن کانفیگ وایرگارد

### ISSUE THREAD

**Issue by Alireza78na** [bepass-org/oblivion#106]
سلام و خسته نباشید.
اگه به این امکان رو اضافه کنید که کانفیگ های وابرگارد غیر از Warp ( مثلا سرویس های شخصی و ... ) رو به برنامه اضافه کنیم خیلی خوب میشه.
اینجوری دیگه میشه به هر وایرگاردی وصل شد و فیلتر کردنشم سخت تر میشه.

**Comment by Amir2367** [comment]
> سلام و خسته نباشید. اگه به این امکان رو اضافه کنید که کانفیگ های وابرگارد غیر از Warp ( مثلا سرویس های شخصی و ... ) رو به برنامه اضافه کنیم خیلی خوب میشه. اینجوری دیگه میشه به هر وایرگاردی وصل شد و فیلتر کردنشم سخت تر میشه.

عالی موافقم خیلی بهتر میشه

**Comment by markpash** [comment]
Duplicate of #173
