### ISSUE TITLE
Interference with the X-Ray core

### ISSUE THREAD

**Issue by itsDantes** [bepass-org/oblivion#109]
thanks for this great work. 

I want to use this library for a part of my program that uses the X-Ray core.  But there is a problem.  To build this library, I have to use an older version of Go, and because of this, I cannot use the functions of this library in my project.  Can you synchronize this library with X-ray core?

i use following Go based library in my project; and as you see it needs version of 1.22.1

https://github.com/XTLS/libXray/blob/8e81fb11f6330780621e441eabdd65e8b23e405e/go.mod#L3

but in your library, to make tun2socks,  it need older version of go. 

https://github.com/bepass-org/oblivion/blob/91fbe72a2a4ef5f2d910c3ef98bedcaf833715f1/app/libs/go.mod#L3

i want to make and Compile both of them in same **.aar** file. because in android you its not possible to use 2 **.aar** because of similar classes. any idea?

**Comment by markpash** [comment]
The next version will start using go 1.21, but we depend on psiphon, which doesn't support 1.22, so we will be stuck there for a while. Sorry :(.

**Comment by markpash** [comment]
The next version will build with 1.22.
