### ISSUE TITLE
 Windows و Android Tv ساپپورت برای

### ISSUE THREAD

**Issue by AbsoluteTakeOff** [bepass-org/oblivion#113]
سلام. اگر ممکن هست برای سیستم ویندوز و اندروید تی وی هم این برنامه رو طراحی کنید. ممنون.
(در حال حاضر نسخه اندروید گوشی روی تی وی جواب میده و دکمه کاننکتو باید موس وصل کنی و بزنی، دوم اینکه توی اپلیکیشن های اندروید تی وی نشون نمیده بذاری تو فیوریت.)

**Comment by vgggy34g55** [comment]
من ذوق دارم برای این برنامه،
لطفا درست کردین کاری کنین با ری استارت دوباره وصل شه

**Comment by MajorMorteza** [comment]
سلام
لطفا پشتیبانی از اندروید تی‌وی رو اصافه کنید. 🙏

**Comment by mmrabbani** [comment]
ممنون که در نسخه آخر، پشتیبانی از تلویزیون را در نسخه ۲ اضافه کردید. ولی همون طور که در تصویر می‌بینید، احتمالا باید در پلی استور کاری انجام دهید که برنامه برای تلویزیون قابل نصب باشد.
![image](https://github.com/bepass-org/oblivion/assets/56675802/ee3b54cb-d648-4f37-bc17-75b2abbb50cf)

**Comment by tireng** [comment]
واقعا به نسخه اندروید تی وی نیاز داریم.اوضاع وی پی ان ها برای اندروید تی وی خیلی بده.

**Comment by markpash** [comment]
I'll provide an update on this matter.
Google Play still hasn't approved the Android TV support yet, but the APK file works fine, so please install from GitHub until Google Play approves it.
Windows version is being built, and you can try it here: https://github.com/bepass-org/oblivion-desktop
