### ISSUE TITLE
(عیدتون مبارک) رو طراحی کردم Android TV نسخه

### ISSUE THREAD

**Issue by AbsoluteTakeOff** [bepass-org/oblivion#114]
آقا من یه نسخه تلویزیون اندروید از Oblivion با استفاده از App Cloner ساختم. **همه چیزش (دکمه تنظیمات، لاگ و درباره برنامه) کار میکنه جز دکمه کانکتش.** فک کنم مدل دکمه کانکت با مدل بقیه دکمه ها فرق میکنه که نمیشه با کنترل تلویزیون دکمه کانکتو زد. **بهرحال با موس وصل کردن و به تلویزیون و زدن دکمه کانکت با موس کار میکنه. لطفا رسیدگی کنید!**
 لینک نسخه اندروید تلویزیون (ی جورایی حجم برنامه با کلون کردن 2 برابر شد🤣):
 https://www.mediafire.com/file/lybi7lefoaa15pw/Oblivion_Android_TV.apk/file
 
 **_راستی من نام پکیچ برنامه رو هم عوض کردم که مشکلی پیش نیاد_**
نام اصلی پکیچ برنامه: **org.bepass.oblivion**
نام جدید برای کلون اندروید تلویزیون: **H3x.TvVer1.oblivi0n**

**Comment by markpash** [comment]
Hi, for user security reasons we much prefer to not share around modified APK files. We are looking to implement these fixes soon! Thanks for your support!
