### ISSUE TITLE
Problems updating license

### ISSUE THREAD

**Issue by shayandavoodii** [bepass-org/oblivion#123]
After triggering the connection, the VPN indicator in the notification section appears for 2 or 3 seconds and then vanishes. After opening the logs section and returning to the home page of the app, the connect button returns to its initial off state. The connection process cannot be aborted after touching the connect button.

https://github.com/bepass-org/oblivion/assets/52105833/e901f7ae-1e85-4a8b-b316-cb54adb80989

Probably the raised error is due to a wrong path:
`msg="failed to load identity" subsystem=warp/account path=./
stuff/primary error="stat stuff/primary/wgcf-identity.json: no
such file or directory'`

Oblivion `v2.0`
Android 14

**Comment by markpash** [comment]
This seems like a bug with your license key. Can you please clear the Oblivion app cache and data and try without a license?

**Comment by shayandavoodii** [comment]
I can't reproduce it anymore since I reinstalled the app. It works fine.
