### ISSUE TITLE
وصل نشدن

### ISSUE THREAD

**Issue by OyenSorta** [bepass-org/oblivion#125]
برای من تقریبا 1 هفتس که نه با همراه اول نه ایرانسل و نه مخابرات وصل میشه امروز هم اپدیت اومد فکر کردم درست شده که نه فرقی نداشت

**Comment by markpash** [comment]
> برای من تقریبا 1 هفتس که نه با همراه اول نه ایرانسل و نه مخابرات وصل میشه امروز هم اپدیت اومد فکر کردم درست شده که نه فرقی نداشت

Can you please wipe the Oblivion app cache and data and install from Google Play?
If you still have problems, please report back.
