### ISSUE TITLE
نسخه ios 

### ISSUE THREAD

**Issue by sahar-km** [bepass-org/oblivion#127]
سلام وقت بخیر، بچه ها این نسخه ios ک تو اپ استور منتشر شده مربوط به این پروژه میشه ؟

 
چندجا اسم Oblivion رو اوردن، حتی قابلیت warp in warp هم گذاشتن ولی حقیقتا نصب نکردم ببینم ادعاشون درسته یانه.
خواستم ببینم اوکیه میشه استفاده کرد، اصلا واسه شماست یا آشناها یا اصلا شاید داره از اسم پروژه سواستفاده میکنه
ممنون میشم یه چک کنید و خبر بدید ❤️

**Comment by markpash** [comment]
اون پروژه به پروژه ما هیچ ارتباطی ندارد. نمی‌دونم کی ساخته، و تا جایی که دیدم، متن باز نیست. من خودم راستش دوست ندارم نصبش کنم، چون که هیچ اعتباری ندارد و نمیتونم اعتماد کنم. پیشنهاد میکنم که از پروژه‌های متن باز (open source) استفاده کنید که کد قابل بررسی داشته باشن.

**Comment by sahar-km** [comment]
> اون پروژه به پروژه ما هیچ ارتباطی ندارد. نمی‌دونم کی ساخته، و تا جایی که دیدم، متن باز نیست. من خودم راستش دوست ندارم نصبش کنم، چون که هیچ اعتباری ندارد و نمیتونم اعتماد کنم. پیشنهاد میکنم که از پروژه‌های متن باز (open source) استفاده کنید که کد قابل بررسی داشته باشن.

 بله کاملا منطقی می‌فرمایید، من هم قرار نیست نصب بکنم ، تنها در صورتی قابل اعتماد بود که تحت نظر شما بالا اومده بود، مرسی از پاسختون، لطف کردید خیلی❤️
