### ISSUE TITLE
Disconnect in standby

### ISSUE THREAD

**Issue by alishk7395** [bepass-org/oblivion#129]
برنامه بعد از خاموش شدن صفحه قطع میشه نیاز داره هر دفعه مجدد ریکانکت بشه.

**Comment by Amir2367** [comment]
> برنامه بعد از خاموش شدن صفحه قطع میشه نیاز داره هر دفعه مجدد ریکانکت بشه.

Yes, I have the same problem

**Comment by peyman47** [comment]
![Screenshot_20240412_193917_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/40957169/46dfa505-6c43-4781-b885-ab2d16fe9aa5)
![Screenshot_20240412_193853_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/40957169/74d3265b-e85a-4407-b618-aa7ec9d63f5f)
@markpash

**Comment by markpash** [comment]
Duplicate of #146
