### ISSUE TITLE
وصل نِمِره!

### ISSUE THREAD

**Issue by mahdiimeni** [bepass-org/oblivion#132]
نسخه قبلی خیلی عالی کار می‌کرد. روی اینترنت مخابرات البته!
اما الان به هیچ عنوان اتصال روی نسخه ۲ برقرار نمی‌شه.

**Comment by mahdiimeni** [comment]
> > نسخه قبلی خیلی عالی کار می‌کرد. روی اینترنت مخابرات البته!
> > اما الان به هیچ عنوان اتصال روی نسخه ۲ برقرار نمی‌شه. 
> 
> میتونی یه تست برام بگیری؟
> لطفاً نسخه جدید (v2) رو نصب کن، بعدش cache و data اپ رو پاک کن، بعد باز کن ببین وصل میشه یا نه. هر نتیجه که گرفتی، لطفاً اینجا کامنت بذار.

خب مثل اینکه درست شد، هم روی مخابرات هم همراه اول ...
اما اگر لایسنس بزنی، باز کار نمی‌کنه!
فقط بدون لایسنس کار می‌کنه.

**Comment by OyenSorta** [comment]
برای من هم همینه نسخه دومم ریختم ولی وصل نمیشه اصلا نمیدونم چکار کنم

**Comment by mahdiimeni** [comment]
> برای من هم همینه نسخه دومم ریختم ولی وصل نمیشه اصلا نمیدونم چکار کنم

گفتن دیگه
کش برنامه رو از قسمت تنظیمات پاک کنید.
روی آیکون برنامه تپ کنید و نگه دارید.
![Screenshot_20240410_164110_One UI Home.jpg](https://github.com/bepass-org/oblivion/assets/40702581/347b24d3-669d-435e-bc8b-037f28d97ea9)

بعدش روی اون علامت i بزنید وارد تنظیمات برنامه می‌شید
از اونجا از بخش storage برید کش برنامه رو پاک کنید.
بدون لایسنس وصل می‌شه اما با لایسنس من نتونستم متصل بشم.
اگر از تنظیمات warp on warp رو هم تیکشو بزنید آی‌پی آلمان میده بهتون.
در حالت معمولی آی‌پی ایران و فقط فیلترینگ رو دور میزنه اما روی تحریم‌ها اثری نداره.

**Comment by mahdiimeni** [comment]
لایسنس رو عوض کردم، لایسنس جدید گرفتم خوشبختانه کار کرد.
