### ISSUE TITLE
Add proxy mode for relive configs(proxy chain)and REMOTE DNS 

### ISSUE THREAD

**Issue by Amir2367** [bepass-org/oblivion#133]
Hello, I suggest to add PROXY, DIRECT DNS and REMOTE DNS in the program settings, like other programs.

With the addition of PROXY, we can create a proxy chain in the main space of the phone in other programs such as Nekobox and relive many configs (because only Warp can relive blocked and limited configs)

By adding DNS, we can block many advertisements and save a lot of internet usage in Iran.
the examples below

https://github.com/bepass-org/oblivion/assets/83357422/cdb782bd-4ba2-4e48-883d-9b6058aa6b0f

**Comment by Amir2367** [comment]
> adding the proxy chain thing may be too much work but I agree with remote dns.
> 
> we can block ads by either : using ad blocking remote dns , OR using geosite and geoip config files.
> 
> adding any of these will block ads.

No matter how time consuming, I think at this stage when Nekobox no longer updates, it will be great, I hope it will be done ❤️

**Comment by debMan** [comment]
This could be done with the help of adding Oblivian as an upstream in other apps like shadowsocks or V2rayNG

**Comment by markpash** [comment]
Let's track this issue in #164
