### ISSUE TITLE
متصل نشدن بر روی شبکه رایتل 

### ISSUE THREAD

**Issue by Alireza-F-kenedy** [bepass-org/oblivion#136]
سلام مارک عزیز ممنون بابت ادامه راه یوسف قبادی
برنامه از نسخه اولیه تا نسخه دو بر روی شبکه رایتل متصل نمیشه با دو تا سه گوشی و سه سیم کارت در دو منطقه مختلف تست کردم متصل نمیشه نمی دونم چرا حتی APN گوشی ipv4/ip6 فعاله ولی وصل نمیشه
ولی روی شبکه همراه اول و ایرانسل بسیار عالی و خوب کار
میکنه
با توجه به اینکه رایتل فیلترینگ شل تری نسبت به همراه اول و ایرانسل داره ولی برنامه Oblivion بر روی رایتل متصل نمی شود

**Comment by markpash** [comment]
Duplicate of #137
