### ISSUE TITLE
cannot stop vpn when its state is connecting

### ISSUE THREAD

**Issue by angry-mob** [bepass-org/oblivion#138]
تو نسخه‌ی جدید موقعی که vpn در حالت connecting قرار داره و بخوای قطعش کنی vpn service قطع میشه اما هسته‌ش همچنان در حال اجرا میمونه و حتما باید یکبار برنامه رو ببندی و بازش کنی.
به احتمال خیلی زیاد این مشکل مربوط به متد stop هسته‌ی برنامه‌ست. تو نسخه‌ی قبلی که با متد shutdown سروبس رو متوقف میکردی این مشکل وجود نداشت

**Comment by Amir2367** [comment]
> تو نسخه‌ی جدید موقعی که vpn در حالت connecting قرار داره و بخوای قطعش کنی vpn service قطع میشه اما هسته‌ش همچنان در حال اجرا میمونه و حتما باید یکبار برنامه رو ببندی و بازش کنی. به احتمال خیلی زیاد این مشکل مربوط به متد stop هسته‌ی برنامه‌ست. تو نسخه‌ی قبلی که با متد shutdown سروبس رو متوقف میکردی این مشکل وجود نداشت

Yes,i have same problem

**Comment by markpash** [comment]
Duplicate issue #147
