### ISSUE TITLE
آی پی ایران

### ISSUE THREAD

**Issue by amirsheikhan** [bepass-org/oblivion#140]
سلام چطوری با آی پی ایران 
همه چی باز میشه مثل اینستاگرام ؟؟؟

**Comment by AR3N4** [comment]
> سلام چطوری با آی پی ایران همه چی باز میشه مثل اینستاگرام ؟؟؟

دوست عزیز این اپلیکیشن بر پایه سرویس کلودفلر هست و IP اختصاص داده شده به آن IP خود کلادفلر هست با لوکیشن ایران.
در صورت تمایل به تغییر IP به کشوری غیر از ایران از تنظیمات گزینه گول (Warp in Warp) را فعال کنید.

**Comment by markpash** [comment]
> > سلام چطوری با آی پی ایران همه چی باز میشه مثل اینستاگرام ؟؟؟
> 
> دوست عزیز این اپلیکیشن بر پایه سرویس کلودفلر هست و IP اختصاص داده شده به آن IP خود کلادفلر هست با لوکیشن ایران. در صورت تمایل به تغییر IP به کشوری غیر از ایران از تنظیمات گزینه گول (Warp in Warp) را فعال کنید.

This is correct, thanks for explaining.
