### ISSUE TITLE
درخواست نسخه ویندوز

### ISSUE THREAD

**Issue by paulvek** [bepass-org/oblivion#142]
سلام و تشکر بابت زحماتتون.
لطفا در صورت امکان یک نسخه ویندوزی هم از این اپ بسازید تا گروه بزرگی از کاربران که تعداد زیادی رو شامل میشن هم استفاده کنن.

**Comment by SadBoyProlific** [comment]
یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد.
https://github.com/Vauth/vox

**Comment by sacanebrahimirad** [comment]
> یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد. https://github.com/Vauth/vox

نجاتمون دادی مدت ها بود دنبالش بودم

**Comment by paulvek** [comment]
> > یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد. https://github.com/Vauth/vox
> 
> نجاتمون دادی مدت ها بود دنبالش بودم

این برای شما کار کرد؟ روی سیستم من کار نکرد.

**Comment by sacanebrahimirad** [comment]
> > > یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد. https://github.com/Vauth/vox
> > 
> > 
> > نجاتمون دادی مدت ها بود دنبالش بودم
> 
> این برای شما کار کرد؟ روی سیستم من کار نکرد.

cfon ro off kon va scan ro on kon , badesh boro to setting windows ghesmate proxy va bad to ghessmate manual setup proxy address ro benevis 127.0.0.1 vali port hamoon bashe va bad save

**Comment by paulvek** [comment]
> > > > یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد. https://github.com/Vauth/vox
> > > 
> > > 
> > > نجاتمون دادی مدت ها بود دنبالش بودم
> > 
> > 
> > این برای شما کار کرد؟ روی سیستم من کار نکرد.
> 
> cfon ro off kon va scan ro on kon , badesh boro to setting windows ghesmate proxy va bad to ghessmate manual setup proxy address ro benevis 127.0.0.1 vali port hamoon bashe va bad save

بعد از انجام این کارها اگه کانکت رو بزنید خودش پروکسی رو توی ویندوز روشن میکنه و چیزهای موردنیازو اضافه میکنه
فقط در بخش پروکسی ویندوز آدرسو به شکل http://socks=127.0.0.1 وارد میکنه که باید همه رو حذف و تبدیل به این 127.0.0.1 کرد یعنی باید http://socks= از اولش حذف بشه چون به این شکل کار نمیکنه!

**Comment by MehranAkbarii** [comment]
> سلام و تشکر بابت زحماتتون. لطفا در صورت امکان یک نسخه ویندوزی هم از این اپ بسازید تا گروه بزرگی از کاربران که تعداد زیادی رو شامل میشن هم استفاده کنن.

سلام من بزودی میخوام روی ساخت نسخه تحت ویندوز oblivion کار کنم ، امیدوارم موفق بشم.

**Comment by paulvek** [comment]
> > سلام و تشکر بابت زحماتتون. لطفا در صورت امکان یک نسخه ویندوزی هم از این اپ بسازید تا گروه بزرگی از کاربران که تعداد زیادی رو شامل میشن هم استفاده کنن.
> 
> سلام من بزودی میخوام روی ساخت نسخه تحت ویندوز oblivion کار کنم ، امیدوارم موفق بشم.

عالیه امیدوارم موفق باشید و لطف میکنید.

**Comment by MehranAkbarii** [comment]
> > > سلام و تشکر بابت زحماتتون. لطفا در صورت امکان یک نسخه ویندوزی هم از این اپ بسازید تا گروه بزرگی از کاربران که تعداد زیادی رو شامل میشن هم استفاده کنن.
> > 
> > 
> > سلام من بزودی میخوام روی ساخت نسخه تحت ویندوز oblivion کار کنم ، امیدوارم موفق بشم.
> 
> نجاتمون میدی واقعاً اگه اینکارو بکنی

تمام سعیمو میکنم تا درستش کنم کتابخونه تحت go رو به c کامپایل کردم ، حالا باید برنامه رو بنویسم. من پروژه رو با net. دارم مینویسم متاسفانه هیچ سورس مشابهی که از wireguard go تحت net. استفاده کنه پیدا نکردم و واسه همین باید خودم کل برنامه رو پیاده کنم که یکم زمان میبره.

**Comment by MehranAkbarii** [comment]
سلام کد go کتابخونه tun2socks.go رو به C کامپایل کردم که توی .net بتونم ازش استفاده کنم برای دور زدن محدودیت های cgo یه تغییرات تو کد go ایجاد کردم ، الان همچی آمادست برای نوشتن کلاینت تحت ویندوز ، اینم ریپوزیتوری گیت هاب که پروژه رو توش قرار میدم.
https://github.com/MehranAkbarii/OblivionWindowsClient

**Comment by paranical** [comment]
> یه نسخه جدیدا پیدا کردم. ولی بر روی system proxy هستش. تست کن شاید به دردت خورد. https://github.com/Vauth/vox

برنامه معرفی شده open source نیست. احتیاط کنید.

**Comment by mrjaycodes** [comment]
سلام نسخه ویندوز اینجاست، 
https://github.com/mrjaycodes/OblivionDesktop

**Comment by paulvek** [comment]
> نامه معرفی شده open source ن

بله در استفاده از این برنامه هرچند سرعت خوبی داره و کار میکنه اما ویندوز اون رو به عنوان تروجان تشخیص داد و هشدار داد. تولی لینک زیر گزارش کردم.
https://github.com/Vauth/vox/issues/7#issuecomment-2072336064

اما یک نسخه به تازگی آقای [NIKJOO](https://github.com/NIKJOO) منتشر کردن همین الان تست گرفتم که بدون مشکل و راحت کار میکنه. و اوپن سورس هست و میتونید استفاده کنید

[](https://github.com/NIKJOO/WarpOnWarp-Windows-Client)

نسخه ی که [mrjaycodes](https://github.com/mrjaycodes) هم در پاسخ قبلی معرفی کردن مشکوکه، چون لینک دانلودش فقط از گوگل دایو هست و فایل ها برای دانلود در خود گیت هاب بارگذاری نشدن و برای دانلود هم باید یک ریکوئست اکسس بخواید تا بتونید دریافت کنید

پس بهترین نسخه فعلا نسخه آقای نیکجو هستش
https://github.com/NIKJOO/WarpOnWarp-Windows-Client

البته سایر دوستان قرار بود یک ریپوی دیگه ازش بزنن نسخه ویندوزی و منتشر کنن نمیدونم این همون نسخه آقای نیکجوئه یا اینکه اونها یکسری افراد دیگه هستن بنابراین اینطوری نسخه های دیگری هم در روزها و هفته های آینده ازش میاد

**Comment by mrjaycodes** [comment]
باسلام، نسخه ی من تروجان نیست، بخاطر فریم ورکی که استافده شده اونطوری نشون میده، و درضمن این ها Embed شده هست یعنی شما میتونید با یک کلیک برنامه رو اجرا کنید

**Comment by mrjaycodes** [comment]
> > نامه معرفی شده open source ن
> 
> بله در استفاده از این برنامه هرچند سرعت خوبی داره و کار میکنه اما ویندوز اون رو به عنوان تروجان تشخیص داد و هشدار داد. تو لینک زیر گزارش کردم. [Vauth/vox#7 (comment)](https://github.com/Vauth/vox/issues/7#issuecomment-2072336064)
> 
> اما یک نسخه به تازگی آقای [NIKJOO](https://github.com/NIKJOO) منتشر کردن همین الان تست گرفتم که بدون مشکل و راحت کار میکنه. و اوپن سورس هست و میتونید استفاده کنید
> 
> نسخه ی که [mrjaycodes](https://github.com/mrjaycodes) هم در پاسخ قبلی معرفی کردن مشکوکه، چون لینک دانلودش فقط از گوگل درایو هست و فایل ها برای دانلود در خود گیت هاب بارگذاری نشدن و برای دانلود هم باید یک ریکوئست اکسس بخواید تا بتونید دریافت کنید
> 
> پس بهترین نسخه فعلا نسخه آقای نیکجو هستش https://github.com/NIKJOO/WarpOnWarp-Windows-Client
> 
> البته سایر دوستان قرار بود یک ریپوی دیگه ازش بزنن نسخه ویندوزی و منتشر کنن نمیدونم این همون نسخه آقای نیکجوئه یا اینکه اونها یکسری افراد دیگه هستن بنابراین اینطوری نسخه های دیگری هم در روزها و هفته های آینده ازش میاد

سلام مجدد، این برنامه توسط شخصی به اسم، RxRLl.dll ساخته شده ولی ایشون از من خواستن که اینو منتشر کنم.
همون ریپوزیتوری خود oblivion من برین، فایل ویندوزی اجرایی شو میبینید.

**Comment by mrjaycodes** [comment]
لینک قبلی باطل شد و این لینک از الآن قابل استفاده است.
https://github.com/mrjaycodes/OblivionDesktop/releases/tag/Oblivion

**Comment by paulvek** [comment]
> لینک قبلی باطل شد و این لینک از الآن قابل استفاده است. https://github.com/mrjaycodes/OblivionDesktop/releases/tag/Oblivion

متشکرم اما فقط بحث دانلود نیست بحث منتشر کردن سورس هست.میتونید از اون شخص سورس دریافت کنید و در گیتهاب پروژه کامل آپ کنید، یا ازش بخواین که خودش این کارو انجام بده؟ تا امکان بررسی کدها وجود داشته باشه از نظر امنیتی و ... بررسی بشه( البته کسی باید باشه تخصص بررسی این موارد رو داشته باشه) به هر حال... هدف از مطرح کردن قرار دادن لینک در گیت هاب این بود که دسترسی به سورس وجود داشته باشه.

**Comment by SadBoyProlific** [comment]
> > نامه معرفی شده open source ن
> 
> بله در استفاده از این برنامه هرچند سرعت خوبی داره و کار میکنه اما ویندوز اون رو به عنوان تروجان تشخیص داد و هشدار داد. تو لینک زیر گزارش کردم. [Vauth/vox#7 (comment)](https://github.com/Vauth/vox/issues/7#issuecomment-2072336064)
> 
> اما یک نسخه به تازگی آقای [NIKJOO](https://github.com/NIKJOO) منتشر کردن همین الان تست گرفتم که بدون مشکل و راحت کار میکنه. و اوپن سورس هست و میتونید استفاده کنید
> 
> نسخه ی که [mrjaycodes](https://github.com/mrjaycodes) هم در پاسخ قبلی معرفی کردن مشکوکه، چون لینک دانلودش فقط از گوگل درایو هست و فایل ها برای دانلود در خود گیت هاب بارگذاری نشدن و برای دانلود هم باید یک ریکوئست اکسس بخواید تا بتونید دریافت کنید
> 
> پس بهترین نسخه فعلا نسخه آقای نیکجو هستش https://github.com/NIKJOO/WarpOnWarp-Windows-Client
> 
> البته سایر دوستان قرار بود یک ریپوی دیگه ازش بزنن نسخه ویندوزی و منتشر کنن نمیدونم این همون نسخه آقای نیکجوئه یا اینکه اونها یکسری افراد دیگه هستن بنابراین اینطوری نسخه های دیگری هم در روزها و هفته های آینده ازش میاد

اره، [Vox](https://github.com/vauth/vox) رو توی [VirtualVirus](https://www.virustotal.com/gui/file/87dc780050f15219bd9cf21b417caf00a62dd2e18e777a9e007f92c2a7f80a6c/detection) تست کردم ایراد داشت،
از چند نفر پرسیدم میگن ایرادی نداره.
در هر صورت نسخه اصلیش اومده انگار بی نیاز شدیم.

**Comment by mrjaycodes** [comment]
> > > نامه معرفی شده open source ن
> > 
> > 
> > بله در استفاده از این برنامه هرچند سرعت خوبی داره و کار میکنه اما ویندوز اون رو به عنوان تروجان تشخیص داد و هشدار داد. تو لینک زیر گزارش کردم. [Vauth/vox#7 (comment)](https://github.com/Vauth/vox/issues/7#issuecomment-2072336064)
> > اما یک نسخه به تازگی آقای [NIKJOO](https://github.com/NIKJOO) منتشر کردن همین الان تست گرفتم که بدون مشکل و راحت کار میکنه. و اوپن سورس هست و میتونید استفاده کنید
> > نسخه ی که [mrjaycodes](https://github.com/mrjaycodes) هم در پاسخ قبلی معرفی کردن مشکوکه، چون لینک دانلودش فقط از گوگل درایو هست و فایل ها برای دانلود در خود گیت هاب بارگذاری نشدن و برای دانلود هم باید یک ریکوئست اکسس بخواید تا بتونید دریافت کنید
> > پس بهترین نسخه فعلا نسخه آقای نیکجو هستش https://github.com/NIKJOO/WarpOnWarp-Windows-Client
> > البته سایر دوستان قرار بود یک ریپوی دیگه ازش بزنن نسخه ویندوزی و منتشر کنن نمیدونم این همون نسخه آقای نیکجوئه یا اینکه اونها یکسری افراد دیگه هستن بنابراین اینطوری نسخه های دیگری هم در روزها و هفته های آینده ازش میاد
> 
> اره، [Vox](https://github.com/vauth/vox) رو توی [VirtualVirus](https://www.virustotal.com/gui/file/87dc780050f15219bd9cf21b417caf00a62dd2e18e777a9e007f92c2a7f80a6c/detection) دیدم ایراد داشت، از چند نفر پرسیدم میگن ایرادی نداره. در هر صورت نسخه اصلیش اومده انگار بی نیاز شدیم.

کدوم نیسخه؟

**Comment by markpash** [comment]
The version we support is available here: https://github.com/bepass-org/oblivion-desktop/releases

Be careful of other versions. Especially versions created by people with a history of unethical behaviour.

**Comment by mrjaycodes** [comment]
> متشکرم اما فقط بحث دانلود نیست بحث منتشر کردن سورس هست.میتونید از اون شخص سورس دریافت کنید و در گیتهاب پروژه کامل آپ کنید، یا ازش بخواین که خودش این کارو انجام بده؟ تا امکان بررسی کدها وجود داشته باشه از نظر امنیتی و ... بررسی بشه( البته کسی باید باشه تخصص بررسی این موارد رو داشته باشه) به هر حال... هدف از مطرح کردن قرار دادن لینک در گیت هاب این بود که دسترسی به سورس وجود داشته باشه.

بله درسته اما سورس دست من نیست، ایشون از من خواستن که اینو منتشر کنم، بهتون قول میدم که نسخه های بعدی چه نسخه رسمی چه نسخه های غیر رسمی، بهتر و پر سرعت تر خواهند بود
