### ISSUE TITLE
Inaccurate GeoIP for Psiphon

### ISSUE THREAD

**Issue by Alireza-F-kenedy** [bepass-org/oblivion#143]
Sometimes it connects in the siphon mode in the German location, and the IP of another country connects
![Uploading Screenshot_20240417_223451_Oblivion.png…]()

**Comment by LordArma** [comment]
I also confirm it.

**Comment by markpash** [comment]
This is due to Inaccurate GeoIP for the servers used in Psiphon. This isn't an Oblivion bug.
