### ISSUE TITLE
تنظیمات پروکسی

### ISSUE THREAD

**Issue by mostafavahdanideh** [bepass-org/oblivion#161]
سلام، لطفا تنظیمات پروکسی مثل آدرس هاست و پروتکلش رو در دسترس قرار بدین الان فقط پورت اتصال برنامه معلومه و تا جایی که فهمیدم تنظیمات پروکسی اَپ الان روی:

Host : 127.0.0.1
Port : 8086
Protocol : SOCKS5

هستش.

**Comment by markpash** [comment]
Duplicate issue #164
