### ISSUE TITLE
update tun2socks lib to last changes

### ISSUE THREAD

**Issue by itsDantes** [bepass-org/oblivion#168]
please update tun2socks lib to last changes. as i see,  Warp-Plus had a many changes and they are still not applied to this app library.

**Comment by markpash** [comment]
> please update tun2socks lib to last changes. as i see, Warp-Plus had a many changes and they are still not applied to this app library.

Don't worry, I am working on both of these projects, I will make updates to the Oblivion app as soon as I think `warp-plus` is ready. :heart:
