### ISSUE TITLE
لود نکردن سایت ها

### ISSUE THREAD

**Issue by mehrdadkh9** [bepass-org/oblivion#17]
موقع استفاده از نت خانگی سایت ها لود نمیشن ولی بقیه نرم افزار ها مشکلی ندارن ولی رو نت موبایل مشکلی نیست

**Comment by mehrdadkh9** [comment]
![Screenshot_20240211_222417_Chrome](https://github.com/bepass-org/oblivion/assets/83773016/f2cc04f9-2f96-4b60-8da0-82a1e8a3c76a)

**Comment by ialireza** [comment]
اینترنت شما چی است؟ تیک گول بزن و بزن اتصال ۳ بار تلاش کنی وصل میشه و باز میشه روی مخابرات

**Comment by mehrdadkh9** [comment]
> اینترنت شما چی است؟ تیک گول بزن و بزن اتصال ۳ بار تلاش کنی وصل میشه و باز میشه روی مخابرات

آسیاتک،تیک گول رو زدم متصل میشه و تو تلگرام یا اینستاگرام مشکلی نداره ولی هیچ سایتی رو باز نمیکنه و ارور بالا رو میده

**Comment by DanielcoderX** [comment]
> > اینترنت شما چی است؟ تیک گول بزن و بزن اتصال ۳ بار تلاش کنی وصل میشه و باز میشه روی مخابرات
> 
> پارس آنلاین،تیک گول رو زدم متصل میشه و تو تلگرام یا اینستاگرام مشکلی نداره ولی هیچ سایتی رو باز نمیکنه و ارور بالا رو میده


Hey, If it's possible share your app log screenshot for further Diagnosis.
