### ISSUE TITLE
error raised while connecting (portable version) on windows x64

### ISSUE THREAD

**Issue by amirhz** [bepass-org/oblivion#172]
At first well done guys for your efforts.
While it's connecting the message is shown: "برنامه برای اجرا نیاز به نصب پاورشل دارد"
please add the correct url to download powershell.
thx

**Comment by markpash** [comment]
Hi @amirhz please make issues relating to the Windows desktop version in following place: https://github.com/bepass-org/oblivion-desktop/issues

**Comment by amirhz** [comment]
My bad!
