### ISSUE TITLE
عدم ثبات سرور ها 

### ISSUE THREAD

**Issue by TechForAll1373** [bepass-org/oblivion#174]
سرور ها متأسفانه هر یک دقیقه قطع می شوند و به جای سرور همان کشور موقعیت مکانی کشوری را می دهد که ربطی به سرور ندارد لطفاً ورژن جدید را با امکانات ارائه دهید

**Comment by mrjaycodes** [comment]
https://github.com/mrjaycodes/OblivionDesktop
this version has many stabilities and compatibilities, you can scan it and use it.

(this app is not made by bepass org made by RxRLl.dll)

**Comment by markpash** [comment]
This app connects to the Cloudflare Warp servers. If you have problems connecting, please provide more details.

- Device Make and Model
- Android Version
- Screenshot of Log page
- ISP
- Settings used
