### ISSUE TITLE
[Problem]: Saving logs on storage

### ISSUE THREAD

**Issue by radiumatic** [bepass-org/oblivion#176]
I'm not an expert on this matter, but I think writing FREQUENT logs on storage wears it down. There should either be an option to change log level, or the logs shouldn't be written to disk.

**Comment by markpash** [comment]
This is a good point. Perhaps it's best that we implement it in such a way that it doesn't write to storage, instead just being temporary in memory.

**Comment by radiumatic** [comment]
As for the TUN implementation, the project currently uses tun2socks. It's *kind of* inefficient. Eg, v2rayNG has more battery usage than NekoBox. 

If I remember correctly, wireguard-go already supports TUN setup on android without root or tun2socks. Take a look at the official [wireguard-android client](https://github.com/WireGuard/wireguard-android).

**Comment by markpash** [comment]
> Pipes? I'm pretty sure almost all languages have some cmd invoking standard library that provides stderr, stdin and stdout as io streams, especially Java.

Yep, something like that pretty much.

> I'm not an Android developer, and I doubt the transition can be done in just one hour, but Java seems a bit outdated for a new app in 2024. Either Kotlin has arguably better community, or they're pretty loud when it comes to the Internet. Even the official Android docs recommend Kotlin.

I'm not an android developer either, I inherited this app after Yousef Ghobadi was arrested. With the number of bugs already, I don't want to switch language.

> Kotlin has Jet Compose (easy UI design and implementation, with riddance of XML), an absurd number of libraries and plenty of official support.

Sure, but I really don't have any experience and don't want to make things worse.



> As for the TUN implementation, the project currently uses tun2socks. It's _kind of_ inefficient. Eg, v2rayNG has more battery usage than NekoBox.

Indeed.

> If I remember correctly, wireguard-go already supports TUN setup on android without root or tun2socks. Take a look at the official [wireguard-android client](https://github.com/WireGuard/wireguard-android).

Yeah I saw that too, but some users want to have socks5 as well, and I don't want to make major changes atm, so I'm gonna keep things as they are and figure out some of the major bugs before fixing the networking code in the shim.

**Comment by radiumatic** [comment]
> I'm not an android developer either, I inherited this app after Yousef Ghobadi was arrested. With the number of bugs already, I don't want to switch language.

That's understandable, though there should be more than enough Kotlin developers in the community to ask help from. 

> Yeah I saw that too, but some users want to have socks5 as well, and I don't want to make major changes atm, so I'm gonna keep things as they are and figure out some of the major bugs before fixing the networking code in the shim.

Can't you reuse code from sing-box? Their TUN implementation is pretty neat, not to mention the "mixed" inbound type. 

On a side note, CF IPs being throttled with the amount of Oblivion users was honestly inevitable. I think adding support for custom wireguard configurations and nudging the free config providers to use wireguard would be a pretty good idea to mitigate that issue.

**Comment by radiumatic** [comment]
@markpash I presume this is fixed and this issue can be closed?

**Comment by inattentive-nerd** [comment]
I don't promise but I might try do a rewrite in Kotlin.
Disclaimer: I am a rookie.

**Comment by inattentive-nerd** [comment]
I don't promise but I might try do a rewrite in Kotlin.
Disclaimer: I am a rookie.

**Comment by radiumatic** [comment]
@markpash any updates?

**Comment by radiumatic** [comment]
Um? @markpash Should this be closed? Is it fixed?

**Comment by markpash** [comment]
yeah hopefully the next release will have the fix

**Comment by radiumatic** [comment]
@markpash Maybe you missed this, but logs are still written to disk and there's no option to change the logging level. Honestly the current approach is correct, but at least logs should be disabled by default or enabled with a mostly silent mode (only reporting errors)
