### ISSUE TITLE
Question ❓

### ISSUE THREAD

**Issue by MmdRza-Eslami** [bepass-org/oblivion#177]
Hello, there is a dns change program called **[Nebulo](https://play.google.com/store/apps/details?id=com.frostnerd.smokescreen)** that can change dns by having the dns port of a vpn program;
a) Does oblivion have a dns port?
b) If the answer to (a) is yes, what is its dns port?

**Comment by markpash** [comment]
The app doesn't have an option to change DNS yet, but it will be added in the future.
