### ISSUE TITLE
App VPN Service Lifetime

### ISSUE THREAD

**Issue by metallica1375** [bepass-org/oblivion#18]
سرویس وی پی انی که اپ میسازد، وقتی فیلترشکن دیگه ای مورد استفاده قرار میگیرد، همچنان روشن میماند و در نوار نوتیفیکیشن گوشی کاربر فعال باقی میماند.

**Comment by markpash** [comment]
This should be fixed in the next release, which will be available soon. :heart:

**Comment by amirgh9367** [comment]
Do you want to create the linux or mac or even windows version ?

**Comment by femdiya** [comment]
> Do you want to create the linux or mac or even windows version ?

This is not the right place to ask for it.
