### ISSUE TITLE
 😒آپدیت نشدن 

### ISSUE THREAD

**Issue by TechForAll1373** [bepass-org/oblivion#182]
چرا آپدیت نمیشه چند وقت همین ۲ مونده لطفاً آپدیت کنید و وضعیت سرور ها را بهتر کنید 😒

**Comment by markpash** [comment]
> با سلام، نسخه oblivion بروز شده و بهتر داره عمل میکنه، البته اضافه کنم که کمی باگ هم داره اما در روز های آینده بهتر از قبل عمل خواهد کرد. 

The updated (open-source) desktop version is available at this link: https://github.com/bepass-org/oblivion-desktop

**Comment by markpash** [comment]
Please use GitHub issues to inform us of bugs and problems. When you see a bug, please create an issue and describe with details.
