### ISSUE TITLE
app not disconnecting or needing a restart if done with quick panel shortcut

### ISSUE THREAD

**Issue by h3sam** [bepass-org/oblivion#187]
When you try to turn on the vpn and then decide to disconnect while it's still trying to connect, it won't let you do it on the app, and if you force it by using the button at quick panel on android, it won't let you connect again unless you close the app completely.

https://github.com/bepass-org/oblivion/assets/87180120/4059bc5b-c2fb-41c2-8c96-d64b07f87412

**Comment by markpash** [comment]
Thanks for the bug report! The video is great and accurately shows the problem, thanks! :heart:
