### ISSUE TITLE
Add app toggle 

### ISSUE THREAD

**Issue by ali2abs** [bepass-org/oblivion#19]
Apps like nekobox and v2rayng has app toggle and its very useful, it let you connect without opening the app. please add this feature

**Comment by ameerhossein** [comment]
[https://github.com/bepass-org/oblivion/pull/25](#25)

**Comment by ameerhossein** [comment]
Available in #25 and 0.8 release. This issue can be closed now 😊

**Comment by ali2abs** [comment]
Thanks a lot
