### ISSUE TITLE
The Android version hopes to add a Chinese Simplified interface as well  

### ISSUE THREAD

**Issue by iD2073** [bepass-org/oblivion#199]
The Android version hopes to add a Chinese Simplified interface as well

**Comment by aintfp** [comment]
中文的https://www.123pan.com/s/cvWVVv-ZX7A3.html
![Screenshot_2024-05-22-18-42-41-023_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/75429131/6980e444-f9cf-4171-a85c-6a644f4d259e)

**Comment by renshengx** [comment]
The Chinese language is not supported, and the interface does not change after modifying the language. It is recommended to modify it similar to the desktop version.

**Comment by markpash** [comment]
Duplicate of #162
