### ISSUE TITLE
Add Windows Version

### ISSUE THREAD

**Issue by mikeesierrah** [bepass-org/oblivion#20]
I know you made a windows version but it's annoying to always do those commands 

Also it's buggy and not as stable as Oblivion

I can't enable TUN mode and there is this bug that just shuts down the whole devices internet when you Close the warp exe some times 

Also I cant I can't make issues there for some reason idk why 

It'd be great if you just made graphical client like oblivion for windows

**Comment by markpash** [comment]
> I would be happy to add a GUI version for Windows using Electron, Repository owner, Please let me know if this is okay with you so I can get started. @uoosef @markpash

There are a few people working on a windows app, feel free to write one yourself too!

**Comment by markpash** [comment]
Available here: https://github.com/bepass-org/oblivion-desktop/releases
