### ISSUE TITLE
مشکل با اینترنت پارس آنلاین و همراه اول

### ISSUE THREAD

**Issue by Irajcoin** [bepass-org/oblivion#203]
آقای پشم فروش خیاری 🥰دو روزه چه با وارپ چه با گول و چه سایفون هیچکدوم متصل نمیشه با وای فای پارس آنلاین و نت همراه اول

**Comment by tnhgm** [comment]
منم همین مشکل رو دارم

**Comment by Alireza-F-kenedy** [comment]
> آقای پشم فروش خیاری 🥰دو روزه چه با وارپ چه با گول و چه سایفون هیچکدوم متصل نمیشه با وای فای پارس آنلاین و نت همراه اول

با استفاده از اپیکیشن از گوگل پلی بریز shadow share قسمت وایگارد کلود فلر تست با نت شاتل شروع به اسکن کن ده تا ای پی میده یکی کپی کن گو درتنظیمات Oblivion قسمت اندپویت قرار بده

**Comment by PARSAALAVI** [comment]
سلام  با اپراتور همراه اول مشکل دارد نسخه جدید ،لطفا بررسی کنید ،خواهش میکنم
