### ISSUE TITLE
عدم اتصال بر روی شاتل

### ISSUE THREAD

**Issue by aliiii73** [bepass-org/oblivion#205]
رو شاتل وصل نمیشه جدیدا

**Comment by Alireza-F-kenedy** [comment]
با استفاده از اپیکیشن از گوگل پلی بریز shadow share  قسمت وایگارد کلود فلر تست با نت شاتل شروع به اسکن کن ده تا ای پی میده یکی کپی کن  گو درتنظیمات Oblivion قسمت اندپویت قرار بده

**Comment by aliiii73** [comment]
بازم وصل نمیشه

در تاریخ چهارشنبه ۲۲ مهٔ ۲۰۲۴،‏ ۰۹:۴۳ Alireza-F-kenedy <
***@***.***> نوشت:

**Comment by markpash** [comment]
Duplicate of #198
