### ISSUE TITLE
عدم اتصال همراه اول و مخابرات

### ISSUE THREAD

**Issue by ALLPAY23** [bepass-org/oblivion#214]
سلام.من نرم افزار  shadowshare رو هم نصب کردم و از اون طریق هم ای پی گرفتم اضافه کردم تو قسمت endpoint  اما اون رو هم ظاهرا فبلتر کردن.
درواقع الان یه دیوسی نشسته این پیام ها رو میخونه میره خبر میده راه حل ها رو هم ببندن.
راه دیگه ای به ذهنتون میرسه دوستان؟

**Comment by markpash** [comment]
Duplicate of #193
