### ISSUE TITLE
کانکت نشدن و کار نکردن با اینترنت همراه اول

### ISSUE THREAD

**Issue by paulvek** [bepass-org/oblivion#215]
**ابتدا بینهایت تشکر میکنم از زحمات و خدمات شما.** در حال حاضر اینترنت همراه اول در بین اپراتورها بهترین و پرسرعت ترین اینترنت هستش. اینو مخصوصا اونهایی درک میکنن که در نقاط وسط شهر یا تحت پوشش عادی نیستن و حتی در روستاها هم همراه اول با سرعت و پایداری بسیار بهتری از ایرانسل کار میکنه.
در مجموع طبق گزارشات و آمارها و تست هایی که در اینترنت هم میتونید جستجو کنید در اکثر نقاط کشور همراه اول همیشه برنده بیشترین سرعت بوده و هست.
از نظر به صرفه بودن هم بسته های متنوع تری از ایرانسل داره مثلا بسته دانلود نامحدود شبانه که از 1 شب تا 11 صبح هست اما ایرانسل زمان بسیار محدودتری (مثلا 6 صبح تا 12 ظهر) برای چنین بسته ای با قیمت بسیار بالاتر و حجم خیلی کمتر در نظر گرفته.
**و مشکل وی پی ان شما** متاسفانه oblivion چه در نسخه دسکتاپ و چه در نسخه اندروید، مثل تمامی وی پی ان های دیگه، یا کلا دسترسی ای نداره یا اینکه بسیار به سختی و محدود کانکت میشه... شما خیلی زحمت کشیدید و خیلی لطف داشتید ولی اگه بتونید مشکل رو در اینترنت همراه اول حل کنید واقعا ممنون میشیم. چون در برخی جاها حتی ایرانسل آنتن هم نداره و امکان استفاده از ایرانسل نیست و دسترسی به خط تلفن و اینترنت ای دی اس ال هم وجود نداره که مناطق زیادی از کشور هستن که چنین شرایطی دارن.
همراه اول هم در نقاط تحت پوشش و هم در نقاط خارج از محدوده سایر اپراتورها با آنتن دهی و سرعت بهتر کار میکنه منتهی پروتکل های متفاوتی داره و فیلترینگ اثر بیشتری روی اون میذاره
هرچند در بعضی از شرایط تفاوتی دیده نمیشد و تمامی اینترنت ها و اپراتورها مسدود و محدود بودن و این بستگی به زمان های مختلف داره.
اما در شرایط چند روز اخیر و حال حاضر همراه اول دسترسی بسیار سختی داره.
توی این روزها فقط دسترسی کمی به argo و v2ray داریم. که کفایت نمیکنه و اگه oblivion برای همراه اول هم اوکی بشه، بسیار عالی میشه. متشکرم.

**Comment by TechForAll1373** [comment]
دقیقا با شما موافقم اصلا اینترنتی وجود ندارد اینترنت از ۱۲ شب ۳ خرداد مثل کره شمالی شده حتی وبسایت های داخلی هم به سختی بالا می‌آید تقصیر آسیاتک می‌باشد آسیاتک شروع کرده به محدودیت و به مابقی سرویس دهنده ها سرایت کرده

**Comment by mansor427** [comment]
برای همراه اول و ایرانسل
2606:4700:d1::c993:5abb:1a22:99d9]:1002

و این دو روی اسیاتک و ایرانسل
188.114.98.224:2408
188.114.98.224:908

با گزینه گول و بدون گول وصل میشه

**Comment by markpash** [comment]
Duplicate of #195

**Comment by paulvek** [comment]
> برای همراه اول و ایرانسل 2606:4700:d1::c993:5abb:1a22:99d9]:1002
> 
> و این دو روی اسیاتک و ایرانسل 188.114.98.224:2408 188.114.98.224:908
> 
> با گزینه گول و بدون گول وصل میشه

ولی من نتونستم با همراه اول کانکت بشم و کارساز نبود.
بعد به نظرم بهترین ارزش افزوده ی oblivision به این بود که خودش اسکن کنه و بتونه بین سرورها بچرخه یا آی پی تمیز بگیره و کاربر با یک کلیک کانکت بتونه متصل بشه. اگه بخوایم هربار دستی کانفیگش کنیم میشه چیزی شبیه v2ray و ... که دردسرهایی ایجاد میکنه. برای من با گول و بدون گول هم همینطور بود متاسفانه. به هر حال خیلی واقعا زحمت میکشن و دستشون درد نکنه که اینو ساختن قصد از گزارش هم فقط اینه که این بهتر بشه وگرنه ما میدونیم که سازندگانش دارن به ما لطف میکنن و ما توقعی ازشون نداریم. ممنون از پیشنهاد و راهکاری که ارائه کردید.
