### ISSUE TITLE
allow LAN prevents connection 

### ISSUE THREAD

**Issue by ramdroid2015** [bepass-org/oblivion#219]
In android version 2 when ever I mark Allow LAN Connection Oblivion can not connect.

**Comment by markpash** [comment]
Can you provide logs please?

**Comment by ramdroid2015** [comment]
I downgraded the app (uninstalled v6 and installed v2) but couldn't reproduce the issue.
Again I updated to v6 and there was no issue.
Thanks for all of your considerations.
