### ISSUE TITLE
قطع روی اینترنت ثابت عصرتلکام

### ISSUE THREAD

**Issue by Saeed9899** [bepass-org/oblivion#228]
سلام متاسفانه کلا وارپ و oblivion روی اینترنت ثابت از کار افتاده اما با نت رایتل وصل میشه لطفا برای این مشکل که تقریبا معضل اینترنت ثابت هاست یه فکری بکنید، از طرفی از قابلیت سایفون هم نمیشه استفاده کرد چون پروتکل وارپ کار نمیکنه، اگر بشه با روشی این دو تا رو با تفکیک از هم استفاده کرد واقعا خوب میشه.

**Comment by amirhosseinamini145** [comment]
قبلا هم اندروید هم ورژن دسک تاپ خیلی که جدید تر هست عالی بود و تعداد کمی مشکل داشتن الان بنظر میرسه فیلترینگ هوشمند همراه با تغییرات ایجاد شده باعث شده تقریبا از کار بیفته هر چند ادمینهای عزیز دارن شبانه روز زحمت میکشن و همه هم دارن  میبینن چقدر سخته ولی واقعا این پروژه بی نظیر و عالی هست بهتر و راحتتر از این نرم افزار فعلا وجود نداره خداکنه زحمات به ثمر بشینه چون عصای دسته همه هست

**Comment by Saeed9899** [comment]
دقیقا با شما موافقم چون فیلتر ایران و چین از لحاظ تکنولوژی ادغام شده برای همین به سرعت و با یک پوشش داره انجام میشه، واقعا تصور نمیکردم به شخصه به خاطر امکانات این برنامه مثل تغییر اندپوینت، و گول نسبت به نسخه اصلی وارپ به طور کلی رو نت ثابت از کار بیفته، امیدوارم زحمات جواب بده و راهکار های دیگه ایی بشه استفاده کرد.

**Comment by amirhosseinamini145** [comment]
روی اندپوینت ۱۸۸.۱۱۴.۹۸.۲۲۴:۲۴۰۸ امتحان کنین برای من روی همه نتها حل شد

**Comment by Saeed9899** [comment]
موقتا مشکل رفع شد
