### ISSUE TITLE
عدم اتصال روی شاتل

### ISSUE THREAD

**Issue by TheRockMilad** [bepass-org/oblivion#237]
روی شاتل هم وصل نمیشه ، البته نسخه اندورید رو تست کردم
سامسونگ اندروید ۱۳

**Comment by DanielcoderX** [comment]
سلام، ممنون میشم اطلاعات بیشتری ارائه بدهید.
آیا در قسمت ارور ارور خاصی به چشم میخوره؟
تنظیمات دیگری رو امتحان کردید ببینید وصل میشه یا نه؟
در صورت امکان از بخش لاگ به صورت برش خورده (crop) اسکرین شات آپلود کنید یا به صورت متنی چندین خط آخر (حداقل 5 خط) رو بفرستید.

**Comment by M3hdiko** [comment]
به نظرم باید جدا از قسمت اند پوینت قسمت پورت تونل را هم تغییر بدیم ولی نمیدونم چند بذاریم

**Comment by TheRockMilad** [comment]
> به نظرم باید جدا از قسمت اند پوینت قسمت پورت تونل را هم تغییر بدیم ولی نمیدونم چند بذاریم

من دقیقا نمیدونم :)
