### ISSUE TITLE
FR : Implement on mikrotik 🥹

### ISSUE THREAD

**Issue by amijafi** [bepass-org/oblivion#24]
Standard wireguard including standard warp can be implemented on Latest Mikrotik devices , it would be nice if this modified warp can be used on mikrotik, no need for psiphon or gool options , the simple scenario would be enough for most cases

**Comment by markpash** [comment]
This is a good idea! I've opened the issue section here: https://github.com/bepass-org/wireguard-go
Please recreate your issue there as this repo is for the Android app.
