### ISSUE TITLE
سلام عدم اتصال در گوشی سامسونگ 

### ISSUE THREAD

**Issue by gholam7534** [bepass-org/oblivion#249]
سلام وقت بخیر از دیروز نرم افزار گوشی اپدیت شد و بعد از اون دیگه وصل نمیشه 
گوشی سامسونگ m52

**Comment by gholam7534** [comment]
![Screenshot_۲۰۲۴۰۵۳۱_۱۶۲۰۰۶_Software update](https://github.com/bepass-org/oblivion/assets/171349070/33f2ca7e-6c02-4a51-8803-cf517bd1de92)

**Comment by soheilrsh** [comment]
Salam

![Uploading 
Screenshot_۲۰۲۴-۰۶-۰۲-۱۰-۴۷-۵۹-۳۵۶_org.bepass.oblivion.jpg…]()
هم مخابرات هم همراه اول استفاده میکنم 
شیائومی  Poco x5 pro 5g
