### ISSUE TITLE
متصل نشدن روی اینترنت همراه اول

### ISSUE THREAD

**Issue by Mhdiqpzx** [bepass-org/oblivion#254]
مناسفانه اخیرا حتی با استفاده از آیپی تمیز وارپ و حتی سایفون امکان اتصال توسط اینترنت اوپراتور همراه اول وجود نداره. در صورت امکان امکاناتی که در حل حاظر داره به نسخه ویندوز اضافه میشه رو روی نسخه اندروید هم اعمال کنید تا بلکم بشه از یه طریقی متصل شد.

**Comment by mhmdnzr** [comment]
دقیقا من هم همین مشکل رو روی تمام خطوط همراه اول داشتم(دائمی و اعتباری)

**Comment by falconer67** [comment]
اول مطمئن شو نقطه دستیابی گوشی پروتکل روی ipv4/ipv6  هست و توی تنظیمات ، دی ان اس دستی یا روی خودکار نباشه و روی خاموش باشه ؛ بعد بیا تو برنامه قسمت اندپوینت یه ipv6 بذار حل میشه

**Comment by Mhdiqpzx** [comment]
> > اول مطمئن شو نقطه دستیابی گوشی پروتکل روی ipv4/ipv6 هست و توی تنظیمات ، دی ان اس دستی یا روی خودکار نباشه و روی خاموش باشه ؛ بعد بیا تو برنامه قسمت اندپوینت یه ipv6 بذار و تیک گول رو بردار حل میشه
> 
> **راه‌حل شما کاملا درست و دقیقه**، اما متاسفانه هنوز IPv6 روی همراه‌اول هم‌مانند ایرانسل در سطح شهر و کشور پوشش دهی ندارد. آیا اطلاعی دارید IPv6 همراه‌اول در چه شهر/منطقه‌ای فعال شده؟
