### ISSUE TITLE
برای ویندوز هم این مسئله رفع کنید

### ISSUE THREAD

**Issue by tablighjonoub** [bepass-org/oblivion#26]
سلام و وقت بخیر امکان داره برای ویندوز هم این امکان فعال کنید

برنامه اصلی وصل نمیشه هر کار می کنیم
ممنون

**Comment by MikeeSierrah** [comment]
باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN

**Comment by MikeeSierrah** [comment]
باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟

**Comment by farshad991** [comment]
> باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟

این روش جوابگو است منتها اگر بخواید در کنار وارپ از V2Ray هم یک سرور رو اجرا کنید جواب نمیده (با proxyfire میشه این کار رو کرد البته هر از گاهی باید برنامه مجدد اجرا کرد).
نمیدونم برنامه ایی برای نسخه ویندوز دارند یا خیر منتها کمال تشکر رو از برنامه نویسان این پروژه دارم ، با اینکه نسخه آزمایشی است بسیار عالی کار میکنه.

**Comment by tablighjonoub** [comment]
> باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟

برای ویندوز این روش جوابگو نیست تست شده

**Comment by MikeeSierrah** [comment]
> > باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟
> 
> برای ویندوز این روش جوابگو نیست تست شده
> 

وقتی با اطمینان میگید جوابگو نیست تست شده فک نکنم درست باشه
ما تست کردیم جواب هم گرفتیم هرچند خیلی باگ ها برخورد کردیم 

Warp -scan 
رو اجرا کنید تا براتون آی‌پی تمیز پیدا کنه بعد متصل بشید

**Comment by tablighjonoub** [comment]
من چنداین بار تست کردام نشد شاید اشتباه رفته باشم نمی دانم اما با تست می کنم تشکر

**Comment by Amyr-Askari** [comment]
> > > باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟
> > 
> > 
> > برای ویندوز این روش جوابگو نیست تست شده
> 
> وقتی با اطمینان میگید جوابگو نیست تست شده فک نکنم درست باشه ما تست کردیم جواب هم گرفتیم هرچند خیلی باگ ها برخورد کردیم
> 
> Warp -scan رو اجرا کنید تا براتون آی‌پی تمیز پیدا کنه بعد متصل بشید

سلام خسته نباشید. این دستور warp -scan رو کجا باید وارد کنیم، چون توی خود cmd ارور ناشناخته میده. یک آموزش کامل تر ازش هست؟ یا خودتون میتونید یک راهنمایی ریز بکنید

**Comment by MikeeSierrah** [comment]
> > > > باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟
> > > 
> > > 
> > > برای ویندوز این روش جوابگو نیست تست شده
> > 
> > وقتی با اطمینان میگید جوابگو نیست تست شده فک نکنم درست باشه ما تست کردیم جواب هم گرفتیم هرچند خیلی باگ ها برخورد کردیم
> > 
> > Warp -scan رو اجرا کنید تا براتون آی‌پی تمیز پیدا کنه بعد متصل بشید
> 
> سلام خسته نباشید. این دستور warp -scan رو کجا باید وارد کنیم، چون توی خود cmd ارور ناشناخته میده. یک آموزش کامل تر ازش هست؟ یا خودتون میتونید یک راهنمایی ریز بکنید

https://youtu.be/KT_cxcKesS0?si=HUw7G38DJknqS4BM 
طبق این آموزش برین 

فقط کافیه بجای اینکه مستقیم بنویسین warp 

دستور warp -h رو وارد کنید و تمامی دستور هارو ببینید 

دستور warp -scan رو بزنید برای اسکن آی‌پی تمیزه

**Comment by MikeESierraH** [comment]
> > MikeESierraH
> 
> دستتون درد نکنه. طبق آموزش رفتم و الان به وارپ وصلم با ریپازیتوری wireguard-go 
> 
> اما یک مشکلی هست اینه که توی سایت ها هنوز آیپی من رو ایران نشون میده، دستوری وجود داره که مثل گزینه گول توی oblivion آیپی ایران رو مخفی کنه و مثلا آلمان رو نشون بده؟ توی دستور warp -h یک گزینه gool دیدم ولی انگار کار نمیکنه. شاید من درست استفاده نمیکنم ازش

امتحان نکردم ولی -cfon باید باشه 

تو خود ریپو ی راهنما گذاشته لیست کشور هارو هم گذاشته

**Comment by h3sam** [comment]
> > > باید از طریق cmd وارپو اجرا کنی بعد بری تو برنامه هایی مثل نکوری و v2rayN ی پراکسی ساکس درست کنی ادرس بزاری 127.0.0.1 پورتشو بزاری 8086 بعد بهش کانکت بشی -- این کارارو کردی ؟
> > 
> > 
> > برای ویندوز این روش جوابگو نیست تست شده
> 
> وقتی با اطمینان میگید جوابگو نیست تست شده فک نکنم درست باشه ما تست کردیم جواب هم گرفتیم هرچند خیلی باگ ها برخورد کردیم
> 
> Warp -scan رو اجرا کنید تا براتون آی‌پی تمیز پیدا کنه بعد متصل بشید

من هم به مشکل مشابهی برخوردم. وقتی `warp -scan` رو ران می‌گیرم بدون مشکل اسکن می‌کنه آی‌پی‌ها رو، ولی به محض این که با یه کانفیگ ساکس می‌خوام وصل بشم ارور زیر رو می‌ده:

`2024/03/03 14:25:13 connect to 188.114.97.155:880 failed: listen udp 188.114.97.155:880: bind: The requested address is not valid in its context.`
کلاینت من همچنین v2rayN هست، و تانل می‌زنم.

**Comment by femdiya** [comment]
حقیقتا هروقت وارپ وصل میشم (چه اپ رسمی چه این) کلا ایپی ایرانه

**Comment by Aldl88** [comment]
دوستانی که برای ویندوز مشکل دارند من روی این repo یه installer هست که راحت فقط با ران کردنش میتونید از فیلتر شکن استفاده کنید https://github.com/Aldl88/warp-plus

**Comment by markpash** [comment]
> دوستانی که برای ویندوز مشکل دارند من روی این repo یه installer هست که راحت فقط با ران کردنش میتونید از فیلتر شکن استفاده کنید

If you have useful changes, please submit a Pull Request so we can have them here. Please do not link users to your compiled binaries.

**Comment by markpash** [comment]
Windows version is available here: https://github.com/bepass-org/oblivion-desktop/releases
