### ISSUE TITLE
Go lang build Error

### ISSUE THREAD

**Issue by behnamnasehi** [bepass-org/oblivion#269]
PS C:\Users\a\StudioProjects\oblivion\app\libs> go run golang.org/x/mobile/cmd/gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o=tun2socks.aar . C:\Users\a\AppData\Local\Temp\go-build3282308728\b001\exe\gomobile.exe: C:\Users\a\go\bin\gobind.exe -lang=go,java -outdir=C:\Users\a\AppData\Local\Temp\gomobile-wor k-3737507334 .aar tun2socks failed: exit status 1 no exported names in the package ".aar" no exported names in the package ".aar" no exported names in the package ".aar" no exported names in the package ".aar"

**Comment by DanielcoderX** [comment]
Hi, try to run like this:
`go run golang.org/x/mobile/cmd/gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o="tun2socks.aar" .`

_Double quotation marks at tun2socks.aar _

**Comment by behnamnasehi** [comment]
solved

**Comment by SorenMika** [comment]
> solved

How did you solve your problem?
I have the same problem

**Comment by binaryb3ast** [comment]
try to run like this:
`go run golang.org/x/mobile/cmd/gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o="tun2socks.aar" .`

Double quotation marks at tun2socks.aar

Please ensure that these are installed: 
Java 17
Gradle 8
Android Gradle Plugin (AGP) 8.1.2
NDK r26b (26.1.10909125)
Go 1.22
