### ISSUE TITLE
با استفاده از ای پی ۶ وصل میشه ولی بدون فعال بودن گول

### ISSUE THREAD

**Issue by falconer67** [bepass-org/oblivion#273]
برای اتصال روی اپراتور همراه اول : 
پروتکل نقطه دستیابی روی ipv4/ipv6 میذاریم ، dns رو خاموش میکنیم ، اندپویت ipv6  می‌ذاریم،  گول رو غیرفعال میکنیم متصل میشه 
مشکل : متصل نشدن هنگام فعال بودن گول با ipv6 و تحریم بخاطر ای پی ایران در برخی از سایت‌ها
`

**Comment by DanielcoderX** [comment]
This is related to the ability of choosing IPV4/6 version which is going to get fixed in the next release
so, I'm going to close this issue
