### ISSUE TITLE
مشکل در بیلد شدن پروژه

### ISSUE THREAD

**Issue by Mikael1993** [bepass-org/oblivion#28]
سلام
موقع بیلد شدن پروژه داخل کلاس OblivionVpnService یه ارور میده من تصویر رو ضمیمه میکنم
مشکل چیه؟ ایا از وی پی ان هست مشکل؟
![1](https://github.com/bepass-org/oblivion/assets/94840296/2e93303e-d5a9-4181-94a0-2e1120eda633)

**Comment by ameerhossein** [comment]
[https://github.com/bepass-org/oblivion/pull/4](Read comitted file)

**Comment by ameerhossein** [comment]
Check the committed file of this PR #4
