### ISSUE TITLE
Connection in apps

### ISSUE THREAD

**Issue by Geekyasspackgod** [bepass-org/oblivion#29]
بعد کانکت شدن حتی با آپشن گول فقط اپ تلگرام کار میکنه ولی همون سرعتش عالیه ولی بقیه اپ ها مثل یوتوب حتی مرورگر هیچ سایتی رو بالا نمیاره
نت همراه اول اندروید ۱۱

**Comment by KingM4tin** [comment]
برای من با همراه اول وصل میشه ولی در حد ۳۰ ثانیه کار میکنه اونم تلگرام با اینکه زده وصل شده
ولی با مخابرات مشکلی ندارم عالیه

**Comment by DanielcoderX** [comment]
Hello.
I'll be glad if you help and share your app log's page screenshot when it's connected.
