### ISSUE TITLE
کارکرد در پس زمینه، پینگ ، حالت تیره ، میزان حجم دیتای ارسال و دریافت شده

### ISSUE THREAD

**Issue by joiniran** [bepass-org/oblivion#296]
با درود 
زمانی که پنل گوشی خاموش میشود با اینکه اپ متصل زده با روشن شدن پنل هیچی دیتایی رد وبدل نمیشود باید قطه و دوباره متصل شد.
حالت مود تیره را ایجاد نمایید.
پینگ همانند نسخه دسکتاپ نمایش داده شود.
میزان حجم دیتای ارسال و دریافت شده نمایش داده شود هم نسخه اندروید و دسکتاپ.
سپاس

**Comment by DanielcoderX** [comment]
درود
همانطور که در این [کامنت](https://github.com/bepass-org/oblivion/issues/292#issuecomment-2182655771) ذکر شده این وضعیت مربوط به گوشی شما میباشد
حالت تیره و باقی امکانات در نسخه بعدی اضافه خواهد شد.
