### ISSUE TITLE
اضافه کردن toggle button 

### ISSUE THREAD

**Issue by Ali265-265** [bepass-org/oblivion#30]
خواهشا یک تاگل باتن به برنامه اضافه کنید تا مثل وی تو ری بتونیم با یک گزینه اتصال رو برقرار کنیم و نیازی به رفتن به داخل برنامه نباشه. اضاف کردن این گزینه در حال حاضر به نظر بنده و خیلی های دیگه ضروری ترین چیزه چون بدون هیچ مشکلی برنامه الان داره کار میکنه و فیچر های دیگه مثل اسپلیت ترافیک و برنامه ها فعلا ضروری نیس. با تشکر از شما بابت ساخت این برنامه شگفت انگیز توی این اوضاع نابسامان اینترنتی

**Comment by uoosef** [comment]
سلام باشه حتما

**Comment by ameerhossein** [comment]
#25 This issue can be closed.
