### ISSUE TITLE
V4版本软件显示连接，但实际上并没有网络。另外一样像windows版本一样有筛选ipv6的功能

### ISSUE THREAD

**Issue by sdfsdfw2** [bepass-org/oblivion#300]
V4版本软件显示连接，但实际上并没有网络。另外一样像windows版本一样有筛选ipv6的功能

**Comment by danirzv** [comment]
> V4版本软件显示连接，但实际上并没有网络。另外一样像windows版本一样有筛选ipv6的功能

The V4 version software shows a connection, but there is actually no network. In addition, like the windows version, it has the function of filtering ipv6

**Comment by it-abc** [comment]
我测试 ipv4 不行，ipv6 自选 ip 的情况下，warpinwarp 模式不行，另外两种模式可以

**Comment by ilanyu** [comment]
see the pr #299 , add ipv4/ipv6

**Comment by DanielcoderX** [comment]
由于该问题即将修复，并且已经有一些补丁可用，我将把它标记为已完成。修复将会包含在下一个版本中。
