### ISSUE TITLE
Xiaomi 6手机Oblivion显示不全

### ISSUE THREAD

**Issue by renshengx** [bepass-org/oblivion#306]
![Screenshot_2024-06-26-06-11-22-355_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/107403232/d7720c61-3406-4952-8cbd-8e1e2fa051fa)
![Screenshot_2024-06-26-06-11-05-973_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/107403232/ff35314a-80de-4093-a8fa-7ee0c3d20bdd)

**Comment by PisLuanyao** [comment]
dpi 问题，不影响使用就忽略吧

**Comment by DanielcoderX** [comment]
由于该问题即将修复，并且已经有一些补丁可用，我将把它标记为已完成。修复将会包含在下一个版本中。
