### ISSUE TITLE
(Proxy mode)پروکسی مود

### ISSUE THREAD

**Issue by BlackDevill11** [bepass-org/oblivion#35]
درود، اگه میشه پروکسی مود رو هم در نظر بگیرید چون خودتون که میدونید توی دنیای مجازی پر از تبلیغات آزار دهنده‌س
که باعث میشه مصرف اینترنت به شدت افزایش پیدا کنه واسه ما ایرانی ها معضله بزرگیه پس مجبوریم از اد بلاک‌ استفاده کنیم تا مصرف نتمون رو کنترول کنیم با تشکر.
 خیلی ممنونم بابت زحماتی که میکشین بدرود.

**Comment by markpash** [comment]
Thanks for the issue, I will see if this is possible to implement. :heart:

**Comment by markpash** [comment]
Duplicate of #164
