### ISSUE TITLE
Infinite connecting state

### ISSUE THREAD

**Issue by shayandavoodii** [bepass-org/oblivion#43]
It is unable to connect successfully and stucks in the connecting state infinitely.
Android: 14
Oblivion `v0.0.9`

https://github.com/bepass-org/oblivion/assets/52105833/8f95f806-c85b-4ed2-a8aa-50941ab8d808

**Comment by smsalehi** [comment]
You should share logs instead of making a video of the UI.

**Comment by shayandavoodii** [comment]
> You should share logs instead of making a video of the UI.

I would if the dev asks.

**Comment by Amillinium** [comment]
Did you try using the [binary](https://github.com/bepass-org/wireguard-go) in termux? If it does not work there too, the issue is out of the context of this repository.

**Comment by shayandavoodii** [comment]
> Did you try using the [binary](https://github.com/bepass-org/wireguard-go) in termux? If it does not work there too, the issue is out of the context of this repository.

No, I didn't. I'll use the following command and report the result ASAP.
```
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/wireguard-go/master/termux.sh)
```

**Comment by shayandavoodii** [comment]
> Did you try using the [binary](https://github.com/bepass-org/wireguard-go) in termux? If it does not work there too, the issue is out of the context of this repository.

Worked.![Screenshot_20240214_173352_Telegram.jpg](https://github.com/bepass-org/oblivion/assets/52105833/d348a374-4773-46ce-bd53-6637ecd41360)

**Comment by shayandavoodii** [comment]
I used the app on another device that runs Android 12 with the same ISP and internet source. The app works perfectly fine. So I'm not sure whether it has an issue with the Android 14 or what.

**Comment by shayandavoodii** [comment]
Following the Termuxs log `Error listening on 127.0.0.1:8086
listen tcp 127.0.0.1:8086: bind: address already in use` provided in my previous comment, I decided to force-stop all of the proxy applications and run the warp through Termux again. As expected, the service started successfully, yet couldn't tunnel the connection as my Telegram didn't connect.
![Screenshot_20240214_183540_Telegram.jpg](https://github.com/bepass-org/oblivion/assets/52105833/4b56c131-4f0a-402d-94ba-e82ae4cdfc8a)

**Comment by ameerhossein** [comment]
Termux does not tunnel the whole device. You have to set the local socks proxy in each app individually. It looks like you didn't set the 127.0.0.1:8086 socks proxy in Telegram. tap the Connecting... text on top bar and add the socks proxy to see if it connects?

**Comment by Amillinium** [comment]
Termux does not tunnel the whole device. You have to set the local socks proxy in each app individually. It looks like you didn't set the 127.0.0.1:8086 socks proxy in Telegram. tap the Connecting... text on top bar and add the socks proxy to see if it connects?

**Comment by shayandavoodii** [comment]
> Termux does not tunnel the whole device. You have to set the local socks proxy in each app individually. It looks like you didn't set the 127.0.0.1:8086 socks proxy in Telegram. tap the Connecting... text on top bar and add the socks proxy to see if it connects?
> 
> 

Thanks for elaborating on that. Yes, it does:
![Screenshot_20240215_171319_Telegram.jpg](https://github.com/bepass-org/oblivion/assets/52105833/2d717323-c0df-4dd1-be41-89a030b221b4)

**Comment by shayandavoodii** [comment]
I decided to try the app one more time to see if it would connect by any chance. It started the connection all of a sudden and it works. It's been hours since the successful connection and it works. However, the download speed isn't as fast as the download speed of Warp through Termux. Please review this if the same procedure is employed by Oblivion.
Feel free to close the issue if you don't need any further investigation regarding the issue.

**Comment by shayandavoodii** [comment]
I faced the same issue when I installed the [Oblivion `v1.0`](https://github.com/bepass-org/oblivion/releases/tag/v1). A decent guess is that the issue is related to the WARP license. The issue was solved when I entered a new license.

**Comment by femdiya** [comment]
> > You should share logs instead of making a video of the UI.
> 
> I would if the dev asks.

Yeah, nobody will help in return.
Good luck with that mindset, weirdo.

**Comment by markpash** [comment]
A video is fine as long as the logs are made visible at some point. Please keep it friendly here.
