### ISSUE TITLE
Chrome incognito mode doesn't work

### ISSUE THREAD

**Issue by Reza-Piri** [bepass-org/oblivion#46]
Chrome incognito mode doesn't work.

Sample error :

This site can’t be reachedThe webpage at 

https://www.google.com/search?q=test+search&oq=test+search&gs_lcrp=#######&client=#####sourceid=chrome-mobile&ie=UTF-8 might be temporarily down or it may have moved permanently to a new web address.

ERR_QUIC_PROTOCOL_ERROR

**Comment by markpash** [comment]
Can you try the latest version in the releases? Please edit your issue to include the version number you installed. :heart:

**Comment by Reza-Piri** [comment]
I'm using the version 1, but the error still remains.

**Comment by femdiya** [comment]
Try disabling the Automatic dns in android settings and chrome settings.
Also provide logs whenever possible.
