### ISSUE TITLE
report bugs

### ISSUE THREAD

**Issue by hosseinTSR** [bepass-org/oblivion#5]
Hello. 
1.When activating the gool option The VPN will automatically disconnect and not connect
2.Output country feature in psiphon settings It does not work properly and does not turn on when activating the VPN application
3.The program relies on the manual IP of Warp and the ability to find the IP automatically has not been applied.
Thanks

**Comment by RezaDorosti** [comment]
When we add license it can not connect.
When we use gool it can not connect.
I use siphon and enter iraq and in what is my ip i get irland

**Comment by yaghobmn** [comment]
ورژن 0.0.5 رو نصب کردم. تو برنامه‌های گوشی نوشته ورژن برنامه 1.5 هست.
