### ISSUE TITLE
Log page issue

### ISSUE THREAD

**Issue by hadiboro** [bepass-org/oblivion#6]
The color of log page texts are white. Better to be changed to darkest color

**Comment by ali2abs** [comment]
Its because of android theme, probably you're using a dark theme if you change it, its gonna be ok.
Of course it will be great if this bug get fixed

**Comment by mmrabbani** [comment]
![Screenshot_2024-02-11-17-31-24-373_org.bepass.oblivion.jpg](https://github.com/bepass-org/oblivion/assets/56675802/149fa20b-8bb3-45b9-91fb-e94fb76adb9f)

I have the same issue in android dark theme

**Comment by ircfspace** [comment]
> I have the same issue in android dark theme

Dark mode version will soon be designed

**Comment by ali2abs** [comment]
> ![Screenshot_2024-02-11-17-31-24-373_org.bepass.oblivion.jpg](https://private-user-images.githubusercontent.com/56675802/303923361-149fa20b-8bb3-45b9-91fb-e94fb76adb9f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjEyMjksIm5iZiI6MTcwNzY2MDkyOSwicGF0aCI6Ii81NjY3NTgwMi8zMDM5MjMzNjEtMTQ5ZmEyMGItOGJiMy00NWI5LTkxZmItZTk0ZmI3NmFkYjlmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE0MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZWNiNDg0ZDRiYTRkMzFmZDBiZDFjMzdlMTE1ZmRhZTIzZWE1MmVjZmI0MDk2N2E4MTVlMTY4MDI5ZDdjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D45MdOXrRlocTdcCfMm0BuIq1Lx2mv76hMLJL8-Zsfs)
> 
> I have the same issue in android dark theme

Turn off the dark mode it will be ok

**Comment by mmrabbani** [comment]
This issue is fixed in the last version and can be closed
