### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by femdiya** [bepass-org/oblivion#67]
This is the error I'm getting while trying to update the app:
![Screenshot_20240223-095708_SAI](https://github.com/bepass-org/oblivion/assets/69072090/6292347b-f261-40b0-ab1c-160739727ae9)

**Comment by femdiya** [comment]
Sorry, looks like I missed something :(
btw the 0.9 version was named 'unsigned' I think so this can be the problem.

**Comment by femdiya** [comment]
@DanielcoderX it's always a good idea to mention these things in changelog or release notes.

**Comment by DanielcoderX** [comment]
> @DanielcoderX it's always a good idea to mention these things in changelog or release notes.

@markpash  yohoo

**Comment by markpash** [comment]
> > @DanielcoderX it's always a good idea to mention these things in changelog or release notes.
> 
> @markpash yohoo

Good point. The release notes have been updated to mention this.
