### ISSUE TITLE
The app can not connect with custom endpoint 

### ISSUE THREAD

**Issue by MrSaeid007** [bepass-org/oblivion#68]
Hi @markpash 

The app will not connected with custom endpoint for example 162.159.193.1:2408
this custom endpoint is ok and working fine in official cloudflare warp for example warp-cli Linux.
Also I tried to connect via connectivity.cloudflareclient.com but no chance.
Can you check?

Thanks.

**Comment by DanielcoderX** [comment]
Hello, ASAP we'll check it and inform you
