### ISSUE TITLE
Bug (Not loading any website or app on Shatel)

### ISSUE THREAD

**Issue by Amir2367** [bepass-org/oblivion#70]
When I turn on oblivion, it doesn't open any site or app except Instagram (my net is Shatel), I suggest you use the strategy that Hidify uses for wireguard go, it works great on all internets.
The video below shows this bug

https://github.com/bepass-org/oblivion/assets/83357422/f5b73194-c015-477a-bfae-317deb38c759

**Comment by DanielcoderX** [comment]
Hello, before everything.
Are you using the latest version? Based your logs looks like there are some debug information which are not available on the latest version.
Please checkout and notify me.

**Comment by Amir2367** [comment]
> Hello, before everything. Are you using the latest version? Based your logs looks like there are some debug information which are not available on the latest version. Please checkout and notify me.



> Hello, before everything. Are you using the latest version? Based your logs looks like there are some debug information which are not available on the latest version. Please checkout and notify me.

Yes, I am using version 1 that was released last , and I would also like to say that most home internets have the same problem that I have. 

![Screenshot_2024-02-23-11-38-32-539_com miui securitycenter](https://github.com/bepass-org/oblivion/assets/83357422/2d5729e5-b73a-4b1b-8a37-adcfd35b4847)

**Comment by Amir2367** [comment]
> Hello, before everything. Are you using the latest version? Based your logs looks like there are some debug information which are not available on the latest version. Please checkout and notify me.

Yes, I am using version 1 that was released last , and I would also like to say that most home internets have the same problem that I have.

![Screenshot_2024-02-23-11-38-32-539_com miui securitycenter](https://github.com/bepass-org/oblivion/assets/83357422/b835e7ad-7c5d-454b-b580-caf4242d930a)

**Comment by LouisBloom2002** [comment]
I have the same problem with shatel. It started last night and was not resolved with the new update.

**Comment by Sosha1996** [comment]
can you try "psiphon"?
im ok with psiphon and warp without gool.

**Comment by Amir2367** [comment]
> can you try "psiphon"? im ok with psiphon and warp without gool.

Personally, I do not prefer to use a Psiphon
 Due to its very low download and upload speed, compared to Warp Cloudflare, it is terrible

**Comment by ameerhossein** [comment]
The built-in cf ip scanner of the Go lib is not really useful IMHO. Because with custom endpoint, vpn connects perfectly on Shatel for example. I guess hiddify is using its own ip scanner. I will look into their code.

**Comment by Amir2367** [comment]
> The built-in cf ip scanner of the Go lib is not really useful IMHO. Because with custom endpoint, vpn connects perfectly on Shatel for example. I guess hiddify is using its own ip scanner. I will look into their code.

Probably as you say
But in any case, checking the Hidify code is very effective in this case, I am waiting for the result, thank you

**Comment by hosseinfarnia** [comment]
> The built-in cf ip scanner of the Go lib is not really useful IMHO. Because with custom endpoint, vpn connects perfectly on Shatel for example. I guess hiddify is using its own ip scanner. I will look into their code.

اگه روشی که هیدیفای برای اتصال به وارپ استفاده میکنه رو پیدا کنید خیلی عالی میشه. چون با یک لمس سریع وصل میشه
