### ISSUE TITLE
مشکلات ورژن 1 

### ISSUE THREAD

**Issue by mahdichm** [bepass-org/oblivion#72]
در صورت خالی بودن پورت کانکت نمیشه ( ورژن های قبل میشد)
در صورت زدن لایسنس کانکنت نمیشه ( ورژن های قبل میشد)
دکمه اتصال دائم روی حالت اتصال برقرار نشد باقی میمونه در صورتی که هریک از موارد بالا رعایت نشه . و کرش میکنه توی این حالت ( حداقل توی شیائومی)

**Comment by mahdichm** [comment]
موارد بالا در حالتی هستن که من اندپوینت وارد میکنم همیشه. 
بدون تغییر اندپوینت اصلا کانکت نمیشه

**Comment by DanielcoderX** [comment]
What do you mean by not connecting? Does the button work on connecting status forever? or even the button doesn't work?

**Comment by mahdichm** [comment]
> What do you mean by not connecting? Does the button work on connecting status forever? or even the button doesn't work?

when there is no port enetred , the text under the button remains ( not connected) but  you can toggle the button on and off. after doing it two times, app crashes.
but if a port is eneterd, button works fine and text under, changes accoordingly

**Comment by ameerhossein** [comment]
Port: Confirmed. Will provide a default port in next release.

License: I guess your license is overused because you deleted the previous version to install the new release. Please check your logs. Check if this is the case like mine:
![Screenshot_20240223_174703_Oblivion.jpg](https://github.com/bepass-org/oblivion/assets/75689502/7c2208aa-a29b-498f-bf38-292755371d01)

**Comment by ameerhossein** [comment]
> وقتی کانکت میشه و می‌خوام با برنامه openvpn for Android بهش وصل بشم بصورت لن ، دیسکانکت میشه برنامه درصورتی که من داخل اوپن وی‌پی‌ان برنامه رو اجازه اش دادم که روی وارپ اعمال نکنه وی‌پی‌ان رو در ورژن قبلی راحت وصل میشد ...

This is the limitation of Android. You cannot connect to two VPNs at the same time. Previous version had a bug which prevented the service from reacting to Android asking it to gracefully disconnect. Actually you used this bug as a feature in previous version. Unfortunately we have no proxy mode at the moment but will be implemented soon.

**Comment by ameerhossein** [comment]
> وقتی کانکت میشه و می‌خوام با برنامه openvpn for Android بهش وصل بشم بصورت لن ، دیسکانکت میشه برنامه درصورتی که من داخل اوپن وی‌پی‌ان برنامه رو اجازه اش دادم که روی وارپ اعمال نکنه وی‌پی‌ان رو در ورژن قبلی راحت وصل میشد ...

This is the limitation of Android. You cannot connect to two VPNs at the same time. Previous version had a bug which prevented the service from reacting to Android asking it to gracefully disconnect. Actually you used this bug as a feature in previous version. Unfortunately we have no proxy mode at the moment but will be implemented soon.

**Comment by mahdichm** [comment]
> Port: Confirmed. Will provide a default port in next release.
> 
> License: I guess your license is overused. because you deleted the previous version to install the new release, your license data was wiped out and you cant register new device using it. Please check your logs. Check if this is the case like mine. You may need to use a fresh license.
> 
> ![Screenshot_20240223_174703_Oblivion.jpg](https://private-user-images.githubusercontent.com/75689502/307349478-7c2208aa-a29b-498f-bf38-292755371d01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTc1NDAsIm5iZiI6MTcwODcxNzI0MCwicGF0aCI6Ii83NTY4OTUwMi8zMDczNDk0NzgtN2MyMjA4YWEtYTI5Yi00OThmLWJmMzgtMjkyNzU1MzcxZDAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE5NDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDAwMDliM2M3OWNmNTliOTMxNzBmZmQzZWUwNWE3NTQ0NzBkOGQ0MjFmYjUwZDc1MWQwMTk2ZDliNTdiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JY9HuUxsfrcEelk-x25BMky99h9ZYmQ2O0Z2PLJ-7I0)

![photo_2024-02-23_23-22-22](https://github.com/bepass-org/oblivion/assets/74412307/9277a833-3ed9-4cd4-a86c-6bdf80b775ce)

Changing the license was giving me the above error at first. but after exiting the app it was magically solved and now I'm connected with the license.

**Comment by mahdichm** [comment]
anothre issue is the infinite back button. no matter how many times you press the back/exit button, it keeps you in the app infintely. (does not exit)

another issue is that switching on the toggle makes it Orange (ON) but the text under remains not connected and does not change to CONNECTING. until it gets connected anf then the texts changes to CONNECTED
