### ISSUE TITLE
Problem in automatic mode (occurs sometimes)

### ISSUE THREAD

**Issue by mohammad35322** [bepass-org/oblivion#79]
Another problem is that on the automatic mode of Psiphon, some sites and even the Google site do not work, but YouTube works, but there is no problem in the location selection like DE or US.The problem is only in automatic mode.

**Comment by mohammad35322** [comment]
https://github.com/bepass-org/oblivion/assets/49150138/f751213f-2227-4925-a430-df9b9bf3238e

**Comment by hosseinfarnia** [comment]
Also web.telegram.org does not open in browser, even with DE and US enabled for me.

**Comment by hosseinfarnia** [comment]
سایت زیر هم با سایفون باز نمیشه
https://www.sammyfans.com

همون ارور بالا رو میده
فکر کنم مشکل از سرورهای خود سایفون باشه

**Comment by mohammad35322** [comment]
As our dear friends said, it seems that the same problem exists even on other locations.
If you have access to a PC, test with the warp core using cmd and system proxy on Windows to see if the problem occurs there as well. If the problem persists, then the problem may be with the Psiphon servers

**Comment by hosseinfarnia** [comment]
> As our dear friends said, it seems that the same problem exists even on other locations. If you have access to a PC, test with the warp core using cmd and system proxy on Windows to see if the problem occurs there as well. If the problem persists, then the problem may be with the Psiphon servers

I don't know how to do this on windows.
Do you have any guidance?

**Comment by mohammad35322** [comment]
There is no special guide, but if you want to test, I can help you If you have telegram, please send a message to this id, I will be happy to guide you🙂🙂😊
https://t.me/AminSH3532
