### ISSUE TITLE
مشکلات ورژن جدید

### ISSUE THREAD

**Issue by dbrabd** [bepass-org/oblivion#82]
ورژن جدید وصل نمیشه
ورژن قبلی وصل میشد. در ورژن قبلی اینستا سرعت خوبی داشت اما تلگرام و واتساپ نه

**Comment by femdiya** [comment]
سلام،
یکم مشکلتونو دقیقتر عرض کنید، وصل نمیشه نداریم.
لطفاً لاگ اپ رو اپلود کنید. لاگ اپ اژ طریق ایکون عنکبوتی شکل در بالای صفحه اپلیکیشن قرار داره، میتونید اسکرین شات بگیرید بفرستید.

**Comment by femdiya** [comment]
در ضمن، امشب اختلال زیاد بود، احتمال هست در روز های آینده کمی اوضاع بهتر بشه.

**Comment by dbrabd** [comment]
سلام
دمتون گرم خدایی
ورژن جدید با لایسنس کلا در حال اتصال هست
لایسنس رو حذف کنی وصل میشه اما چیزی برای من باز نمیکنه
چشم شات میگیرم
![Uploading Screenshot_2024-02-25-02-07-44-259_org.bepass.oblivion.jpg…]()

**Comment by dbrabd** [comment]
![Uploading Screenshot_2024-02-25-02-07-44-259_org.bepass.oblivion.jpg…]()

**Comment by dbrabd** [comment]
![Uploading Screenshot_2024-02-25-02-07-44-259_org.bepass.oblivion.jpg…]()

**Comment by femdiya** [comment]
@dbrabd نمیدونم چرا عکسا باز نمیشن ببین میتونی تو یه سرویس اپلود موقت اپلودش کنی
درضمن آره، اوایلش منم این مشکلو داشتم، تو لاگ نگاه کردم دیدم که نوشته بود error 400 max devices connected یا همچین چیزی، رفتم داخل خود اپلیکیشن وارپ و بعضی دستگاه هارو حذف کردم
دقت کن که هر لایسنس ۵ نفر ظرفیت داره

**Comment by dbrabd** [comment]
درست شد الان. لایسنسی که میگیرم از اون ۵ نفره ها نیس
شاید دیشب بخاطر اختلال اینترنت بوده
اینستا رو خیلی خوب جواب میده اما تلگرام و واتساپ رو نه. کسی میدونه دلیلش چیه؟
البته من نت شاتل دارم تا یکماه پیش وارپ عالی کار میکرد یهو قطع شد

**Comment by joiniran** [comment]
درود ورژن 1 برروی نت ثابت شاتل با اینکه متصل میزنه چیزی رو وا نمیکنه ، مورد بعدی قبلا در مورد سریال نامبر پلاس به اقا یوسف گفته بودم و قرار شد بود حل کنه این مشکل رو، با حذف اپ قبلی و نصب جدیدتر با وارد کردن سریال قبلی با وجود اینکه فقط بر روی این اپ استفاده شده متصل نمیشود باید سریال جدید از ربات گرفت . 
![Screenshot_20240226-133432_Oblivion](https://github.com/bepass-org/oblivion/assets/123999344/a9ecab71-1c07-4bde-9864-a3097b75a57f)
