### ISSUE TITLE
ورژن ۱

### ISSUE THREAD

**Issue by drbehzad** [bepass-org/oblivion#84]
وصل نمیشه 
![Uploading Screenshot_20240225_162105_Oblivion.jpg…]()

**Comment by Hesamsong** [comment]
سلام با نت  همراه وصل میشه ‌ولی با نت شاتل میزنه متصل ولی کار نمیکه نه رو حال وارپ نه سایفون

**Comment by Hesamsong** [comment]
![Screenshot_20240226_145007_Oblivion](https://github.com/bepass-org/oblivion/assets/161314512/41776573-9acb-4666-acdf-ecb47c49eb47)
![Uploading Screenshot_20240226_144953_Oblivion.jpg…]()

**Comment by femdiya** [comment]
@drbehzad مثل اینکه اسکرین شات کامل آپلود نشده.

**Comment by Hesamsong** [comment]
![Uploading Screenshot_20240226_144953_Oblivion.jpg…]()

**Comment by Hesamsong** [comment]
قسمت دوم
![Uploading Screenshot_20240226_144953_Oblivion.jpg…]()

**Comment by Hesamsong** [comment]
![Screenshot_20240226_144953_Oblivion](https://github.com/bepass-org/oblivion/assets/161314512/d36486db-d56a-4492-b451-20c77088c63d)
ددوم

**Comment by Amir2367** [comment]
> ![Screenshot_20240226_144953_Oblivion](https://private-user-images.githubusercontent.com/161314512/307825427-d36486db-d56a-4492-b451-20c77088c63d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTQ5OTgsIm5iZiI6MTcwOTAxNDY5OCwicGF0aCI6Ii8xNjEzMTQ1MTIvMzA3ODI1NDI3LWQzNjQ4NmRiLWQ1NmEtNDQ5Mi1iNDUxLTIwYzc3MDg4YzYzZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNjE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmVkMWNlODU2Y2Y3NjE1YjAxYmU3OWRhMTkwY2U2OTZhOTkzODE3MWE0NjNhZjdjNDkyYTNmMzRmYjcxY2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DvzFWyx5ayw4wZ-6yQfHA3D02cFSeQzwAR826BkU1ss) ددوم

مشکل شاتل warp in warp هست با تک وارپ مشکلی نداره که امیدوارم دوستان زودتر مشکلو حل کنن

**Comment by hosseinfarnia** [comment]
> > ![Screenshot_20240226_144953_Oblivion](https://private-user-images.githubusercontent.com/161314512/307825427-d36486db-d56a-4492-b451-20c77088c63d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTQ5OTgsIm5iZiI6MTcwOTAxNDY5OCwicGF0aCI6Ii8xNjEzMTQ1MTIvMzA3ODI1NDI3LWQzNjQ4NmRiLWQ1NmEtNDQ5Mi1iNDUxLTIwYzc3MDg4YzYzZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNjE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmVkMWNlODU2Y2Y3NjE1YjAxYmU3OWRhMTkwY2U2OTZhOTkzODE3MWE0NjNhZjdjNDkyYTNmMzRmYjcxY2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DvzFWyx5ayw4wZ-6yQfHA3D02cFSeQzwAR826BkU1ss) ددوم
> 
> مشکل شاتل warp in warp هست با تک وارپ مشکلی نداره که امیدوارم دوستان زودتر مشکلو حل کنن

وارپ در وارپ فرقش با تک وارپ چیه؟
سرعتش کمتر میشه؟
