### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hosseinfarnia** [bepass-org/oblivion#86]
به نظر من اگه یه قابلیت اضافه بشه که فیلترشکن کانفیگهای مختلف خودش داشته باشه و موقع اتصال بتونه نوع اپراتور رو تشخیص بده و بر اساس نوع اپراتور، کانفیگی که باهاش سازگاری بیشتر داره انتخاب کنه و وصل بشه خیلی خوب میشه
مثلا اونی که به شاتل وصل میشه به کانفیگی که با شاتل سازگار هست وصل بشه و الی آخر

عذر خواهی میکنم اگه اصلاحات و عبارات غیر تخصصی به کار بردم. چون چیزی از این روش وارپ سر در نمیارم. فقط خواستم منظورم رو برسونم

**Comment by markpash** [comment]
With the current method of the app, this isn't really possible. We will try to improve connectivity on all ISPs as best as we can.
