### ISSUE TITLE
روی نت مخابرات از امروز کار نمیکنه

### ISSUE THREAD

**Issue by Darkoferik** [bepass-org/oblivion#92]
امروز  8 اسفند ساعت 4 دیگه آبلیویون وصل نمیشه. نه سایفون نه وارپ

**Comment by hosseinfarnia** [comment]
اختلال هست
بدون فیلترشکن هم باز نمیشه

**Comment by allahyar** [comment]
I force closed the app once, the problem was solved

**Comment by hosseinfarnia** [comment]
الآن مثل اینکه درست شد خودش
