### ISSUE TITLE
مشکل در اتصال

### ISSUE THREAD

**Issue by Kasra3382** [bepass-org/oblivion#93]
![Screenshot_2024-02-27-20-43-52-162_org.bepass.oblivion.jpg](https://github.com/bepass-org/oblivion/assets/70064517/cb3ce6d9-2a33-4432-84fc-b87a85af43ec)

**Comment by hosseinfarnia** [comment]
امروز اختلال هست رو مخابرات
اصلا چیزی باز نمیشه
بدون فیلترشکن امتحان کردی؟

**Comment by Kasra3382** [comment]
اره بدون فیلترشکن یا با یه فیلترشکن دیگه اوکیه با این اپ خفن که همه چیش خوب بود وصل نمیشه

**Comment by femdiya** [comment]
نتت مخابرات یا شاتله؟
چون واسه شاتل خیلیا مشکل داشتن، و من که نتم مخابراته (خلیج فارس آنلاین) واسه اونم وصل نمیشه.
ظاهرا endpoint هارو بستن رو نت خونگی.

**Comment by mohammad35322** [comment]
![Screenshot_۲۰۲۴-۰۲-۲۸-۱۷-۰۶-۵۴-۱۸۸_com.twitter.android.jpg](https://github.com/bepass-org/oblivion/assets/49150138/3cfd9caf-a16a-42b1-af0e-535777bad9d6)
