### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by Drkingman** [bepass-org/oblivion#94]
Hello, in the next update, please design the graphics of the app so that the first two pictures are smaller and the oblivion text is not displayed in half. Thank you.

**Comment by femdiya** [comment]
"Oblivion text is not displayed in half"?????
Can you provide a screenshot because for me it's ok.
![Screenshot_20240228-005621_Oblivion](https://github.com/bepass-org/oblivion/assets/69072090/43a81ef9-d647-4eb7-978b-f9eea3b40a16)

**Comment by hosseinfarnia** [comment]
فکر کنم منظورش از oblivion نصفه عکس زیر هست:
این گوشی صفحه نمایشش کوچکتر هست:
![IMG_20240228_115344_173](https://github.com/bepass-org/oblivion/assets/23297863/fe14ea57-c89e-4df7-854a-2f838dbed63b)
این هم صفحه ای که اول میاد:
![IMG_20240228_115343_936](https://github.com/bepass-org/oblivion/assets/23297863/3e65e042-a1d1-470b-870b-d24678aedacd)

حالا این یک گوشی دیگه هست با صفحه نمایش بزرگتر:
اینجا هم کلمه oblivion یک کمی نصفه نماش داده میشه:
![Screenshot_20240228_115238_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/23297863/794f9c11-704e-4952-a32a-d8ef6525d8b9)

![Screenshot_20240228_115247_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/23297863/d0193cae-0c15-46cb-ae72-8d7646f6c35c)

فکر کنم هر چی صفحه نمایش کوچکتر باشه نوشته‌ها تو در تو تر نمایش داده میشه

**Comment by hosseinfarnia** [comment]
![IMG_20240228_125636_754](https://github.com/bepass-org/oblivion/assets/23297863/ea841b6a-314a-4a5c-9f54-296b0c3af203)
این شکلی هست تو صفحه کوچکتر

**Comment by femdiya** [comment]
خب این مشکل از text size و dpi صفحتون هست
برای بنده با ردمی نوت ۱۱ مشکلی نداره.

**Comment by hosseinfarnia** [comment]
> خب این مشکل از text size و dpi صفحتون هست برای بنده با ردمی نوت ۱۱ مشکلی نداره.

گذاشتم رو حالت نرمال بهتر شد ولی باز یک کم مشکل داره تو نمایش متن

**Comment by femdiya** [comment]
> > خب این مشکل از text size و dpi صفحتون هست برای بنده با ردمی نوت ۱۱ مشکلی نداره.
> 
> گذاشتم رو حالت نرمال بهتر شد ولی باز یک کم مشکل داره تو نمایش متن

با small یا very small هم امتحان کنید.
یا اگه ادم ریسک پذیری هستید، از تنظیمات developer option برید dpi رو تغییر بدید.

**Comment by hosseinfarnia** [comment]
> > > خب این مشکل از text size و dpi صفحتون هست برای بنده با ردمی نوت ۱۱ مشکلی نداره.
> > 
> > 
> > گذاشتم رو حالت نرمال بهتر شد ولی باز یک کم مشکل داره تو نمایش متن
> 
> با small یا very small هم امتحان کنید. یا اگه ادم ریسک پذیری هستید، از تنظیمات developer option برید dpi رو تغییر بدید.

تست کردم بدتر شد
همون نرمال خوبه
