### ISSUE TITLE
Issue Encountered While Building Go Libraries

### ISSUE THREAD

**Issue by hosseinghanbarigit** [bepass-org/oblivion#99]
When running the final command to import necessary libs, I encountered the following issue.
I would appreciate it if you could guide me.

```
C:\Users\<USERNAME>\AppData\Local\Temp\go-build985011904\b001\exe\gomobile.exe: C:\Users\<USERNAME>\go\bin\gobind.exe -lang=go,java -outdir=C:\Users\<USERNAME>\AppData\Local\Temp\gomobile-work-25645764 .aar tun2socks failed: exit status 1
no exported names in the package ".aar"
no exported names in the package ".aar"
no exported names in the package ".aar"
no exported names in the package ".aar"

exit status 1
```

**Comment by DanielcoderX** [comment]
```
go run golang.org/x/mobile/cmd/gomobile init
go run golang.org/x/mobile/cmd/gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o=tun2socks.aar .
```
### Did you run these commands as well? Please notice that you have to use go version 1.20 ~ 1.20.13

**Comment by hosseinghanbarigit** [comment]
@DanielcoderX 

Yes, I have written the commands correctly as shown in the image below. The version of GO is also 20.
![Screenshot](https://github.com/bepass-org/oblivion/assets/22788197/3096fc83-f5ec-4e85-8c7b-481d1df20436)

**Comment by DanielcoderX** [comment]
It may seem ridiculous but the problem is with your shell(mostly UNICODE issues related to terminal font)😂
try using like this **(add double quotation mark)**

`$ gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o="tun2socks.aar" .
`

**Comment by hosseinghanbarigit** [comment]
> It may seem ridiculous but the problem is with your shell(mostly UNICODE issues related to terminal font)😂 try using like this **(add double quotation mark)**
> 
> `$ gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o="tun2socks.aar" . `

Thank you! It turns out the problem was something I hadn't paid attention to, and it's quite ridiculous! 😂
